import type { DashboardLang } from './dashboard-data'

export const DASHBOARD_LOCALES = {
  fr: 'fr-FR',
  ar: 'ar-MA',
  en: 'en-US',
  es: 'es-ES',
}

export function dashboardLocale(lang: DashboardLang) {
  return DASHBOARD_LOCALES[lang] || DASHBOARD_LOCALES.en
}

const EN_DASHBOARD_COPY = {
  sections: {
    overview: {
      label: 'Overview',
      description: 'Executive KPIs, service alerts, and a fast read on customer satisfaction.',
    },
    analytics: {
      label: 'Analytics',
      description: 'Trends, score distribution, and question-level feedback analysis.',
    },
    feedback: {
      label: 'Feedback',
      description: 'Search, filter, and inspect every customer submission in detail.',
    },
    operations: {
      label: 'Operations',
      description: 'Location readiness, service issues, and operational follow-up.',
    },
    collection: {
      label: 'Collection',
      description: 'Public form access, QR assets, and form question management.',
    },
    settings: {
      label: 'Settings',
      description: 'Business profile, branding, plan visibility, and workspace controls.',
    },
  },
  common: {
    brandTagline: 'Customer feedback workspace',
    open: 'Open',
    save: 'Save settings',
    saveChanges: 'Save changes',
    publishChanges: 'Publish changes',
    addQuestion: 'Add question',
    downloadPng: 'Download PNG',
    refreshPreview: 'Refresh',
    openForm: 'Open form',
    openLiveForm: 'Open live form',
    copyFormLink: 'Copy form link',
    copiedLink: 'Copied link',
    copyFailed: 'Copy failed',
    openNavigation: 'Open navigation',
    closeNavigation: 'Close navigation',
    collapseSidebar: 'Collapse sidebar',
    expandSidebar: 'Expand sidebar',
    reportingRange: 'Reporting range',
    trendResolution: 'Trend resolution',
    analyticsTrendResolution: 'Analytics trend resolution',
    searchFeedback: 'Search feedback',
    filterFeedback: 'Filter feedback',
    sortFeedback: 'Sort feedback',
    searchPlaceholder: 'Search comments or question names',
    noData: 'No data',
    noCategory: 'No category',
    noWrittenComment: 'No written comment',
    noWrittenCommentLong: 'No written comment was left on this response.',
    noScore: 'No score',
    positive: 'Positive',
    neutral: 'Neutral',
    attention: 'Attention',
    status: 'Status',
    weakestQuestion: 'Weakest question',
    questionScores: 'Question scores',
    customerComment: 'Customer comment',
    feedbackDetails: 'Feedback details',
    closeFeedbackDetails: 'Close feedback details',
    submitted: 'Submitted',
    overallScoreSuffix: 'overall score',
    questionWord: 'Question',
    newQuestion: 'New question',
    draftQuestion: 'Draft question',
    frenchLabel: 'French label',
    arabicLabel: 'Arabic label',
    englishLabel: 'English label',
    spanishLabel: 'Spanish label',
    required: 'Required',
    responseSingular: 'response',
    responsePlural: 'responses',
    resultSingular: 'result',
    resultPlural: 'results',
    questionSingular: 'question',
    questionPlural: 'questions',
    itemSingular: 'item',
    itemPlural: 'items',
    slotSingular: 'slot',
    slotPlural: 'slots',
    ratedAreaSingular: 'rated area',
    ratedAreaPlural: 'rated areas',
    languageLabelSingular: 'language label filled',
    languageLabelPlural: 'language labels filled',
    removeQuestion: 'Remove question',
    moveUp: 'Move up',
    moveDown: 'Move down',
    fromResponses: 'from',
    lastUpdated: 'Last updated',
    publicAccess: 'Public access',
    ready: 'Ready',
    inactive: 'Inactive',
    notConfigured: 'Not configured',
    optional: 'Optional',
    connected: 'Connected',
    generated: 'Generated',
    previewAvailable: 'Preview available',
    liveFormReady: 'Live form ready',
    setupNeeded: 'Setup needed',
    previousPeriodFlat: 'Flat vs previous period',
    previousPeriodSuffix: 'vs previous period',
    pointsSuffix: ' pts',
    lowScoreShare: 'low-score share',
    currentWindow: 'Current window',
    activePeriods: 'Active periods',
    quietPeriods: 'Quiet periods',
    peakVolume: 'Peak volume',
    bestRatedPeriod: 'Best-rated period',
    averageVolume: 'Average volume',
    latestPeriod: 'Latest period',
    periodsInView: 'periods in view',
    noVolumeDataYet: 'No volume data yet',
    noScoredPeriodsYet: 'No scored periods yet',
    noResponses: 'No responses',
    noResponsesLatestPeriod: 'No responses recorded in the latest period.',
    noPeakVolumeYet: 'Volume will appear here once responses start arriving.',
    noScoredPeriodYet: 'No scored period is available yet.',
    averageResponsesAcrossPeriods: 'Average responses across active periods in the selected window.',
    averageRatingWord: 'average',
    busiestPeriodSuffix: 'in the busiest period',
    closeQrPreview: 'Close QR preview',
    qrPreviewTitle: 'QR preview',
    qrPreviewHeading: 'Scan the live feedback form comfortably',
    qrPreviewCopy:
      'Use this larger preview from another phone or device when you need to scan the live feedback form quickly.',
    openBusinessPhotoPreview: 'Open larger business photo preview',
    closeBusinessPhotoPreview: 'Close business photo preview',
    businessPhoto: 'Business photo',
    businessPhotoCopy: 'Use this larger view to inspect the uploaded business photo comfortably.',
    signedInUser: 'Signed in user',
    replacePhoto: 'Replace photo',
    uploadPhoto: 'Upload photo',
    photoUploaded: 'Photo uploaded',
    noPhotoYet: 'No photo yet',
    removePhoto: 'Remove photo',
    clickPhotoToEnlarge: 'Click the photo to enlarge it.',
    signOut: 'Sign out',
    tryAgain: 'Try again',
    dashboardLoadError: 'Dashboard could not load',
    dashboardLoadErrorCopy:
      'Something went wrong while preparing the workspace. Try again to reload the latest data.',
    noStructuredRatingsTitle: 'No structured ratings',
    noStructuredRatingsCopy:
      'This feedback entry only contains the overall score and any written comment.',
    photoRemoved: 'Business photo removed successfully.',
    photoRemoveError: 'Could not remove business photo.',
    firstQuestionInLiveForm: 'First question in the live form',
    positionPrefix: 'Position',
    positionInLiveOrderSuffix: 'in the live order',
    unpublishedChanges: 'Unpublished changes',
    liveFormSynced: 'Live form synced',
    draftSyncedWithLiveForm: 'Draft synced with live form',
    changesWaitingToPublish: 'Changes waiting to publish',
    configureInSettings: 'Configure in Settings',
    openGoogleReviews: 'Open Google reviews',
    formBuilderEyebrow: 'Form builder',
    languageCoverage: 'Language coverage',
  },
  header: {
    eyebrow: 'Workspace dashboard',
    updating: 'Updating workspace view',
  },
  options: {
    resolutions: { day: 'Day', week: 'Week', month: 'Month' },
    feedbackFilters: {
      all: 'All',
      attention: 'Attention',
      positive: 'Positive',
      commented: 'Commented',
    },
    feedbackSorts: {
      newest: 'Sort: Newest',
      oldest: 'Sort: Oldest',
      highest: 'Sort: Highest score',
      lowest: 'Sort: Lowest score',
    },
    planStatuses: {
      active: 'Active',
      trial: 'Trial',
      past_due: 'Past due',
      suspended: 'Suspended',
    },
  },
  notices: {
    settingsSaved: 'Business settings updated successfully.',
    settingsError: 'Could not save business settings.',
    logoSaved: 'Business photo updated successfully.',
    logoError: 'Could not upload business photo.',
    logoRemoved: 'Business photo removed successfully.',
    logoRemoveError: 'Could not remove business photo.',
    questionLimit: 'The form can contain up to 10 questions.',
    frenchRequired: 'A French label is required before adding a new question.',
    questionAdded: 'Question added to the draft form.',
    keepOneQuestion: 'The form must keep at least one question.',
    noForm: 'No feedback form exists for this workspace yet.',
    publishNeedsQuestion: 'Add at least one question before publishing.',
    publishError: 'Could not publish form questions.',
    publishSuccess: 'Live form questions updated successfully.',
  },
  overview: {
    metrics: {
      averageRating: 'Average rating',
      averageRatingNote: 'Overall satisfaction trend for the selected reporting window.',
      totalFeedback: 'Total feedback',
      totalFeedbackNote: 'Every submission received in the current reporting window.',
      satisfactionRate: 'Satisfaction rate',
      satisfactionRateNote: 'Share of responses scoring 4/5 or higher.',
      negativeAlerts: 'Negative alerts',
      negativeAlertsNote: 'Low-rating responses that deserve fast operational review.',
    },
    reportingPulseTitle: 'Reporting pulse',
    reportingPulseCopy:
      'A lighter read on response momentum across the selected window, grouped by resolution.',
    noFeedbackTitle: 'No feedback in this range',
    noFeedbackCopy: 'Widen the date range or wait for new responses to start filling the dashboard.',
    watchlistTitle: 'Operational watchlist',
    watchlistCopy: 'The most important service and experience signals to review right now.',
    watchlistEmptyTitle: 'No urgent service issues',
    watchlistEmptyCopy:
      'The current data window looks healthy. New risks will appear here as feedback changes.',
    recentFeedbackTitle: 'Recent feedback',
    recentFeedbackCopy: 'Latest customer responses with the fastest path into detailed review.',
    recentFeedbackEmptyTitle: 'No recent feedback yet',
    recentFeedbackEmptyCopy:
      'Once customers submit feedback, the latest responses will be surfaced here.',
    performanceSnapshotTitle: 'Performance snapshot',
    performanceSnapshotCopy:
      'A concise summary of service health, category quality, and comment coverage.',
    strongestCategory: 'Strongest category',
    weakestCategory: 'Weakest category',
    commentCoverage: 'Comment coverage',
    feedbackMix: 'Feedback mix',
    noCategoryData: 'No category data yet',
    watchlistAttentionTitleSuffix: 'low-rating submissions require follow-up',
    watchlistAttentionCopy:
      'Scores below 3/5 signal service recovery opportunities that should be reviewed quickly.',
    watchlistWeakestTitleSuffix: 'is the weakest service area',
    watchlistWeakestCopySuffix: 'average with',
    watchlistWeakestCopyTail: 'in the selected window.',
    watchlistDriftTitle: 'Average rating is softening vs the previous period',
    watchlistDriftCopyTail: 'Review the most recent negative comments for context.',
    watchlistCommentTitle: 'Written comments are still sparse',
    watchlistCommentCopyPrefix: 'Only',
    watchlistCommentCopySuffix:
      'of customers left written context, which limits issue diagnosis.',
  },
  analytics: {
    ratingsTrendTitle: 'Ratings trend',
    ratingsTrendCopy: 'Track response volume and average score over time by day, week, or month.',
    trendEmptyTitle: 'Trend analytics need fresh data',
    trendEmptyCopy:
      'There is not enough feedback in the selected window to build a reliable trend.',
    ratingsDistributionTitle: 'Ratings distribution',
    ratingsDistributionCopy: 'A score-by-score breakdown of the overall rating experience.',
    distributionEmptyTitle: 'Distribution unavailable',
    distributionEmptyCopy:
      'Score distribution becomes useful once the selected date range contains real feedback.',
    sentimentMixAria: 'Feedback sentiment mix',
    questionPerformanceTitle: 'Question performance',
    questionPerformanceCopy:
      'Question-by-question scoring to pinpoint what customers value and where service slips.',
    questionEmptyTitle: 'Question analytics need more data',
    questionEmptyCopy:
      'Question-level insights will appear as soon as customers rate the live form questions.',
    recurringIssuesTitle: 'Recurring issues',
    recurringIssuesCopy:
      'Weak categories that are showing up often enough to deserve operational action.',
    recurringIssuesEmptyTitle: 'No recurring issue pattern',
    recurringIssuesEmptyCopy:
      'As soon as a question becomes a consistent problem, it will be highlighted here.',
    takeawaysTitle: 'Trend takeaways',
    takeawaysCopy: 'Context around how much signal exists in this analytics window.',
  },
  feedback: {
    title: 'Feedback list',
    copy: 'Search comments, sort by score or date, and open full submission details in a side drawer.',
    tableDate: 'Date',
    tableScore: 'Score',
    tableWeakestArea: 'Weakest area',
    tableComment: 'Comment',
    tableStatus: 'Status',
    emptyTitle: 'No feedback matches these filters',
    emptyCopy: 'Try a wider date range or clear the active search, filter, and sort combination.',
  },
  operations: {
    currentLocationTitle: 'Current location snapshot',
    currentLocationCopy:
      'Today the workspace maps to a single business entity, so this panel acts as the live location overview.',
    location: 'Location',
    city: 'City',
    sector: 'Sector',
    latestFeedback: 'Latest feedback',
    noFeedbackYet: 'No feedback yet',
    branchesTitle: 'Branches and locations',
    branchesCopy: 'Prepared for multi-location analytics, while staying honest about the current backend limits.',
    branchesEmptyTitle: 'Branch comparison is not available yet',
    branchesEmptyCopy:
      'The backend currently stores a single business workspace without branch entities or per-location submission ownership. Once those models exist, this area can show top and worst-performing locations.',
    serviceInsightsTitle: 'Service insights',
    serviceInsightsCopy:
      'Operational reading of the weakest categories, even before staff-level tracking exists.',
    serviceInsightsEmptyTitle: 'Not enough operational signal',
    serviceInsightsEmptyCopy:
      'As more responses arrive, service issues and recurring weak spots will be easier to separate from noise.',
    checklistTitle: 'Operational checklist',
    checklistCopy: 'Action prompts for managers based on current product and data readiness.',
    checklistLowScoreTitle: 'Review low-scoring feedback daily',
    checklistLowScoreNone:
      'No low-scoring submissions are currently surfacing in this reporting window.',
    checklistLowScoreNeedsAttentionSuffix: 'still need attention in the selected window.',
    checklistFormTitle: 'Keep the live form aligned with operations',
    checklistFormNone: 'No live questions are configured yet.',
    checklistFormConfiguredSuffix: 'currently drive customer feedback collection.',
    checklistCommentTitle: 'Improve written context from guests',
    checklistCommentCoveragePrefix: 'Written feedback coverage is at',
    checklistCommentGoodTail: 'which gives better qualitative detail.',
    checklistCommentLowPrefix: 'Written feedback coverage is only',
    checklistCommentLowTail: 'so issue diagnosis still depends heavily on score patterns.',
    checklistDimensionsTitle: 'Prepare branch and staff dimensions',
    checklistDimensionsCopy:
      'Multi-branch and staff performance views need backend tables for locations, staff members, and submission relationships.',
  },
  collection: {
    distributionTitle: 'Distribution and QR',
    distributionCopy:
      'Keep collection assets compact, accessible, and easy to distribute without crowding the editor.',
    collectionStatusEyebrow: 'Collection status',
    feedbackFormAccessTitle: 'Feedback form access',
    collectionStatusReadyCopy:
      'Guests can open the live form immediately through the public URL and QR access.',
    collectionStatusMissingCopy: 'No feedback form is currently attached to this workspace.',
    liveFormUrlEyebrow: 'Live form URL',
    liveFormUrlTitle: 'Share the public feedback flow',
    publicUrlLabel: 'Public URL',
    reviewChannelEyebrow: 'Review channel',
    reviewChannelTitle: 'Google review destination',
    reviewChannelConnectedCopy:
      'Send guests to an external review page after they complete the feedback flow.',
    reviewChannelMissingCopy:
      'Add a Google review link when you want to pair private feedback collection with public reviews.',
    qrUtilityEyebrow: 'QR utility',
    qrUtilityTitle: 'Printable QR access',
    qrUtilityCopy: 'Refresh the preview or download a PNG without leaving the builder.',
    qrUtilityHint: 'Click the preview to open a larger scan view.',
    questionBuilderTitle: 'Question builder',
    questionBuilderCopy:
      'Build and localize the live feedback form with a cleaner editor designed for fast scanning and confident publishing.',
    builderEyebrow: 'Form builder',
    builderLeadTitle: 'Design the question flow guests will rate',
    builderLeadCopy:
      'French stays the required source label. Arabic, English, and Spanish can be refined before publishing without leaving this workspace.',
    newQuestionEyebrow: 'New question',
    newQuestionTitle: 'Compose the next prompt before adding it to the draft',
    newQuestionCopy:
      'Draft the main wording once, then tighten the localized versions so guests see a polished form in every language.',
    upToTenQuestions: 'Up to 10 total questions',
    noQuestionsTitle: 'No questions configured',
    noQuestionsCopy:
      'Start with the composer above to create the first multilingual question for the live feedback form.',
    frenchHelper: 'Primary live label and required source field.',
    arabicHelper: 'Shown to Arabic-speaking guests and should read naturally in RTL.',
    englishHelper: 'Optional localized wording for English-speaking guests.',
    spanishHelper: 'Optional localized wording for Spanish-speaking guests.',
  },
  settings: {
    businessTitle: 'Business settings',
    businessCopy: 'Core workspace details used across the feedback experience.',
    businessName: 'Business name',
    plan: 'Plan',
    googleReviewUrl: 'Google review URL',
    planStatus: 'Plan status',
    brandingTitle: 'Branding and workspace',
    brandingCopy: 'Keep the admin workspace polished and aligned with the business brand.',
    workspaceOwner: 'Workspace owner',
    planGuidance: 'Plan guidance',
  },
} as const

type Widen<T> =
  T extends string ? string :
  T extends number ? number :
  T extends boolean ? boolean :
  T extends Array<infer U> ? Array<Widen<U>> :
  T extends object ? { [K in keyof T]: Widen<T[K]> } :
  T

export type DashboardCopy = Widen<typeof EN_DASHBOARD_COPY>

export const DASHBOARD_COPY: Record<DashboardLang, DashboardCopy> = {
  en: EN_DASHBOARD_COPY,
  fr: {
    ...EN_DASHBOARD_COPY,
    sections: {
      overview: {
        label: 'Vue d’ensemble',
        description: 'KPIs clés, alertes de service et lecture rapide de la satisfaction client.',
      },
      analytics: {
        label: 'Analyses',
        description: 'Tendances, répartition des notes et analyse du feedback par question.',
      },
      feedback: {
        label: 'Retours',
        description: 'Recherchez, filtrez et consultez chaque réponse client en détail.',
      },
      operations: {
        label: 'Opérations',
        description: 'Suivi opérationnel, risques de service et priorités terrain.',
      },
      collection: {
        label: 'Collecte',
        description: 'Accès public au formulaire, QR et gestion des questions.',
      },
      settings: {
        label: 'Paramètres',
        description: 'Profil de l’établissement, identité visuelle, plan et contrôle de l’espace.',
      },
    },
    common: {
      ...EN_DASHBOARD_COPY.common,
      brandTagline: 'Espace de feedback client',
      open: 'Ouvrir',
      save: 'Enregistrer les paramètres',
      saveChanges: 'Enregistrer les modifications',
      publishChanges: 'Publier les modifications',
      addQuestion: 'Ajouter une question',
      downloadPng: 'Télécharger le PNG',
      refreshPreview: 'Actualiser',
      openForm: 'Ouvrir le formulaire',
      openLiveForm: 'Ouvrir le formulaire live',
      copyFormLink: 'Copier le lien du formulaire',
      copiedLink: 'Lien copié',
      copyFailed: 'Échec de la copie',
      openNavigation: 'Ouvrir la navigation',
      closeNavigation: 'Fermer la navigation',
      collapseSidebar: 'Réduire la barre latérale',
      expandSidebar: 'Déployer la barre latérale',
      reportingRange: 'Période analysée',
      trendResolution: 'Granularité de tendance',
      analyticsTrendResolution: 'Granularité analytique',
      searchFeedback: 'Rechercher dans les retours',
      filterFeedback: 'Filtrer les retours',
      sortFeedback: 'Trier les retours',
      searchPlaceholder: 'Rechercher dans les commentaires ou les questions',
      noData: 'Aucune donnée',
      noCategory: 'Aucune catégorie',
      noWrittenComment: 'Aucun commentaire écrit',
      noWrittenCommentLong: 'Aucun commentaire écrit n’a été laissé sur cette réponse.',
      noScore: 'Sans note',
      positive: 'Positif',
      neutral: 'Neutre',
      attention: 'À surveiller',
      status: 'Statut',
      weakestQuestion: 'Question la plus faible',
      questionScores: 'Scores par question',
      customerComment: 'Commentaire client',
      feedbackDetails: 'Détail du feedback',
      closeFeedbackDetails: 'Fermer le détail du feedback',
      submitted: 'Soumis',
      overallScoreSuffix: 'note globale',
      questionWord: 'Question',
      newQuestion: 'Nouvelle question',
      draftQuestion: 'Question brouillon',
      frenchLabel: 'Libellé français',
      arabicLabel: 'Libellé arabe',
      englishLabel: 'Libellé anglais',
      spanishLabel: 'Libellé espagnol',
      required: 'Obligatoire',
      responseSingular: 'réponse',
      responsePlural: 'réponses',
      resultSingular: 'résultat',
      resultPlural: 'résultats',
      questionSingular: 'question',
      questionPlural: 'questions',
      itemSingular: 'élément',
      itemPlural: 'éléments',
      slotSingular: 'place',
      slotPlural: 'places',
      ratedAreaSingular: 'dimension notée',
      ratedAreaPlural: 'dimensions notées',
      languageLabelSingular: 'libellé langue renseigné',
      languageLabelPlural: 'libellés langue renseignés',
      removeQuestion: 'Supprimer la question',
      moveUp: 'Monter',
      moveDown: 'Descendre',
      fromResponses: 'sur',
      lastUpdated: 'Dernière mise à jour',
      publicAccess: 'Accès public',
      ready: 'Prêt',
      inactive: 'Inactif',
      notConfigured: 'Non configuré',
      optional: 'Optionnel',
      connected: 'Connecté',
      generated: 'Généré',
      previewAvailable: 'Aperçu disponible',
      liveFormReady: 'Formulaire live prêt',
      setupNeeded: 'Configuration requise',
      previousPeriodFlat: 'Stable vs période précédente',
      previousPeriodSuffix: 'vs période précédente',
      pointsSuffix: ' pts',
      lowScoreShare: 'part de notes faibles',
      currentWindow: 'Fenêtre actuelle',
      activePeriods: 'Périodes actives',
      quietPeriods: 'Périodes calmes',
      peakVolume: 'Pic de volume',
      bestRatedPeriod: 'Période la mieux notée',
      averageVolume: 'Volume moyen',
      latestPeriod: 'Dernière période',
      periodsInView: 'périodes affichées',
      noVolumeDataYet: 'Pas encore de volume exploitable',
      noScoredPeriodsYet: 'Aucune période notée pour le moment',
      noResponses: 'Aucune réponse',
      noResponsesLatestPeriod: 'Aucune réponse enregistrée sur la dernière période.',
      noPeakVolumeYet: 'Le volume apparaîtra ici dès que des réponses arriveront.',
      noScoredPeriodYet: 'Aucune période notée n’est disponible pour le moment.',
      averageResponsesAcrossPeriods:
        'Moyenne des réponses sur les périodes actives de la fenêtre sélectionnée.',
      averageRatingWord: 'de moyenne',
      busiestPeriodSuffix: 'sur la période la plus chargée',
      closeQrPreview: 'Fermer l’aperçu du QR',
      qrPreviewTitle: 'Aperçu du QR',
      qrPreviewHeading: 'Scannez le formulaire de feedback plus confortablement',
      qrPreviewCopy:
        'Utilisez cet aperçu agrandi depuis un autre téléphone ou appareil pour scanner rapidement le formulaire live.',
      openBusinessPhotoPreview: 'Ouvrir l’aperçu agrandi de la photo',
      closeBusinessPhotoPreview: 'Fermer l’aperçu de la photo',
      businessPhoto: 'Photo de l’établissement',
      businessPhotoCopy:
        'Utilisez cette vue agrandie pour vérifier confortablement la photo téléchargée.',
      signedInUser: 'Utilisateur connecté',
      replacePhoto: 'Remplacer la photo',
      uploadPhoto: 'Téléverser une photo',
      photoUploaded: 'Photo importée',
      noPhotoYet: 'Aucune photo',
      removePhoto: 'Supprimer la photo',
      clickPhotoToEnlarge: 'Cliquez sur la photo pour l’agrandir.',
      signOut: 'Se déconnecter',
      tryAgain: 'Réessayer',
      dashboardLoadError: 'Le tableau de bord n’a pas pu se charger',
      dashboardLoadErrorCopy:
        'Une erreur est survenue pendant la préparation de l’espace. Réessayez pour recharger les dernières données.',
      noStructuredRatingsTitle: 'Aucune note détaillée',
      noStructuredRatingsCopy:
        'Cette réponse contient uniquement la note globale et un éventuel commentaire écrit.',
      photoRemoved: 'La photo de l’établissement a été supprimée avec succès.',
      photoRemoveError: 'Impossible de supprimer la photo de l’établissement.',
      firstQuestionInLiveForm: 'Première question du formulaire live',
      positionPrefix: 'Position',
      positionInLiveOrderSuffix: 'dans l’ordre live',
      unpublishedChanges: 'Modifications non publiées',
      liveFormSynced: 'Formulaire live synchronisé',
      draftSyncedWithLiveForm: 'Le brouillon correspond au formulaire live',
      changesWaitingToPublish: 'Des modifications attendent la publication',
      configureInSettings: 'À configurer dans Paramètres',
      openGoogleReviews: 'Ouvrir Google Reviews',
      formBuilderEyebrow: 'Éditeur du formulaire',
      languageCoverage: 'Couverture linguistique',
    },
    header: {
      eyebrow: 'Dashboard de l’espace',
      updating: 'Mise à jour de la vue en cours',
    },
    options: {
      resolutions: { day: 'Jour', week: 'Semaine', month: 'Mois' },
      feedbackFilters: {
        all: 'Tout',
        attention: 'À surveiller',
        positive: 'Positif',
        commented: 'Commenté',
      },
      feedbackSorts: {
        newest: 'Tri : plus récent',
        oldest: 'Tri : plus ancien',
        highest: 'Tri : meilleure note',
        lowest: 'Tri : note la plus basse',
      },
      planStatuses: {
        active: 'Actif',
        trial: 'Essai',
        past_due: 'Paiement en retard',
        suspended: 'Suspendu',
      },
    },
    notices: {
      settingsSaved: 'Les paramètres de l’établissement ont été mis à jour.',
      settingsError: 'Impossible d’enregistrer les paramètres de l’établissement.',
      logoSaved: 'La photo de l’établissement a été mise à jour.',
      logoError: 'Impossible de téléverser la photo de l’établissement.',
      logoRemoved: 'La photo de l’établissement a été supprimée.',
      logoRemoveError: 'Impossible de supprimer la photo de l’établissement.',
      questionLimit: 'Le formulaire peut contenir jusqu’à 10 questions.',
      frenchRequired: 'Un libellé français est requis avant d’ajouter une nouvelle question.',
      questionAdded: 'La question a été ajoutée au brouillon.',
      keepOneQuestion: 'Le formulaire doit conserver au moins une question.',
      noForm: 'Aucun formulaire de feedback n’existe encore pour cet espace.',
      publishNeedsQuestion: 'Ajoutez au moins une question avant de publier.',
      publishError: 'Impossible de publier les questions du formulaire.',
      publishSuccess: 'Les questions live ont été mises à jour avec succès.',
    },
    overview: {
      ...EN_DASHBOARD_COPY.overview,
      metrics: {
        averageRating: 'Note moyenne',
        averageRatingNote: 'Tendance globale de satisfaction sur la période sélectionnée.',
        totalFeedback: 'Total des retours',
        totalFeedbackNote: 'Toutes les réponses reçues pendant la période analysée.',
        satisfactionRate: 'Taux de satisfaction',
        satisfactionRateNote: 'Part des réponses notées 4/5 ou plus.',
        negativeAlerts: 'Alertes négatives',
        negativeAlertsNote: 'Réponses à faible note qui méritent une revue rapide.',
      },
      reportingPulseTitle: 'Pouls de l’activité',
      reportingPulseCopy:
        'Lecture allégée du rythme des réponses sur la fenêtre sélectionnée, regroupée par granularité.',
      noFeedbackTitle: 'Aucun feedback sur cette période',
      noFeedbackCopy: 'Élargissez la période ou attendez de nouvelles réponses pour alimenter le dashboard.',
      watchlistTitle: 'Watchlist opérationnelle',
      watchlistCopy: 'Les signaux de service et d’expérience à traiter en priorité maintenant.',
      watchlistEmptyTitle: 'Aucun sujet de service urgent',
      watchlistEmptyCopy:
        'La fenêtre de données actuelle semble saine. Les nouveaux risques apparaîtront ici si le feedback évolue.',
      recentFeedbackTitle: 'Retours récents',
      recentFeedbackCopy: 'Dernières réponses client avec accès rapide à la revue détaillée.',
      recentFeedbackEmptyTitle: 'Pas encore de retours récents',
      recentFeedbackEmptyCopy:
        'Dès que les clients enverront du feedback, les dernières réponses remonteront ici.',
      performanceSnapshotTitle: 'Vue de performance',
      performanceSnapshotCopy:
        'Résumé concis de la santé du service, de la qualité par catégorie et de la couverture des commentaires.',
      strongestCategory: 'Catégorie la plus forte',
      weakestCategory: 'Catégorie la plus faible',
      commentCoverage: 'Couverture des commentaires',
      feedbackMix: 'Répartition du feedback',
      noCategoryData: 'Pas encore de données par catégorie',
      watchlistAttentionTitleSuffix: 'retours à faible note nécessitent un suivi',
      watchlistAttentionCopy:
        'Les notes inférieures à 3/5 signalent des opportunités de recovery à traiter rapidement.',
      watchlistWeakestTitleSuffix: 'est la zone de service la plus faible',
      watchlistWeakestCopySuffix: 'de moyenne avec',
      watchlistWeakestCopyTail: 'sur la période sélectionnée.',
      watchlistDriftTitle: 'La note moyenne se tasse par rapport à la période précédente',
      watchlistDriftCopyTail: 'Consultez les derniers commentaires négatifs pour le contexte.',
      watchlistCommentTitle: 'Les commentaires écrits restent rares',
      watchlistCommentCopyPrefix: 'Seulement',
      watchlistCommentCopySuffix:
        'des clients ont laissé un contexte écrit, ce qui limite le diagnostic.',
    },
    analytics: {
      ...EN_DASHBOARD_COPY.analytics,
      ratingsTrendTitle: 'Tendance des notes',
      ratingsTrendCopy:
        'Suivez le volume de réponses et la note moyenne dans le temps par jour, semaine ou mois.',
      trendEmptyTitle: 'Les tendances ont besoin de données récentes',
      trendEmptyCopy: 'Il n’y a pas assez de feedback sur cette fenêtre pour construire une tendance fiable.',
      ratingsDistributionTitle: 'Répartition des notes',
      ratingsDistributionCopy: 'Vue score par score de l’expérience globale.',
      distributionEmptyTitle: 'Répartition indisponible',
      distributionEmptyCopy:
        'La répartition devient utile dès que la période sélectionnée contient de vraies réponses.',
      sentimentMixAria: 'Répartition du sentiment du feedback',
      questionPerformanceTitle: 'Performance par question',
      questionPerformanceCopy:
        'Lecture question par question pour identifier ce que les clients apprécient et où le service décroche.',
      questionEmptyTitle: 'Les analyses par question ont besoin de plus de données',
      questionEmptyCopy:
        'Les insights par question apparaîtront dès que les clients noteront les questions du formulaire live.',
      recurringIssuesTitle: 'Problèmes récurrents',
      recurringIssuesCopy:
        'Catégories faibles qui reviennent assez souvent pour justifier une action opérationnelle.',
      recurringIssuesEmptyTitle: 'Aucun schéma récurrent',
      recurringIssuesEmptyCopy:
        'Dès qu’une question devient un problème régulier, elle sera mise en évidence ici.',
      takeawaysTitle: 'Enseignements de tendance',
      takeawaysCopy: 'Contexte sur le niveau réel de signal disponible dans cette fenêtre analytique.',
    },
    feedback: {
      title: 'Liste des retours',
      copy:
        'Recherchez dans les commentaires, triez par note ou par date, et ouvrez le détail dans un panneau latéral.',
      tableDate: 'Date',
      tableScore: 'Score',
      tableWeakestArea: 'Zone la plus faible',
      tableComment: 'Commentaire',
      tableStatus: 'Statut',
      emptyTitle: 'Aucun feedback ne correspond à ces filtres',
      emptyCopy:
        'Essayez une période plus large ou réinitialisez la combinaison actuelle de recherche, filtre et tri.',
    },
    operations: {
      currentLocationTitle: 'Vue du site actuel',
      currentLocationCopy:
        'Aujourd’hui, l’espace correspond à une seule entité business. Ce panneau sert donc de vue live du site.',
      location: 'Site',
      city: 'Ville',
      sector: 'Secteur',
      latestFeedback: 'Dernier retour',
      noFeedbackYet: 'Pas encore de retours',
      branchesTitle: 'Agences et sites',
      branchesCopy:
        'Prêt pour l’analytique multi-sites, tout en restant transparent sur les limites actuelles du backend.',
      branchesEmptyTitle: 'La comparaison des sites n’est pas encore disponible',
      branchesEmptyCopy:
        'Le backend stocke actuellement un seul espace business sans entités agence ni propriété des réponses par site. Une fois ces modèles disponibles, cette zone pourra comparer les meilleures et les moins bonnes implantations.',
      serviceInsightsTitle: 'Insights service',
      serviceInsightsCopy:
        'Lecture opérationnelle des catégories les plus faibles, même avant un suivi par collaborateur.',
      serviceInsightsEmptyTitle: 'Signal opérationnel insuffisant',
      serviceInsightsEmptyCopy:
        'À mesure que plus de réponses arrivent, il sera plus facile de distinguer les vrais problèmes du bruit.',
      checklistTitle: 'Checklist opérationnelle',
      checklistCopy: 'Actions recommandées pour les managers selon l’état actuel du produit et des données.',
      checklistLowScoreTitle: 'Revoir quotidiennement les retours à faible note',
      checklistLowScoreNone:
        'Aucune réponse à faible note ne remonte actuellement dans cette fenêtre de reporting.',
      checklistLowScoreNeedsAttentionSuffix: 'restent à traiter sur la fenêtre sélectionnée.',
      checklistFormTitle: 'Garder le formulaire live aligné avec l’opérationnel',
      checklistFormNone: 'Aucune question live n’est configurée pour le moment.',
      checklistFormConfiguredSuffix: 'pilotent actuellement la collecte client.',
      checklistCommentTitle: 'Renforcer le contexte écrit des clients',
      checklistCommentCoveragePrefix: 'La couverture écrite est à',
      checklistCommentGoodTail: 'ce qui apporte davantage de détail qualitatif.',
      checklistCommentLowPrefix: 'La couverture écrite n’est que de',
      checklistCommentLowTail:
        'donc le diagnostic dépend encore fortement des schémas de note.',
      checklistDimensionsTitle: 'Préparer les dimensions agence et staff',
      checklistDimensionsCopy:
        'Les vues multi-sites et collaborateur exigent des tables backend pour les sites, les membres du staff et leurs relations avec les réponses.',
    },
    collection: {
      distributionTitle: 'Distribution et QR',
      distributionCopy:
        'Gardez les actifs de collecte compacts, accessibles et faciles à diffuser sans encombrer l’éditeur.',
      collectionStatusEyebrow: 'Statut de collecte',
      feedbackFormAccessTitle: 'Accès au formulaire de feedback',
      collectionStatusReadyCopy:
        'Les clients peuvent ouvrir immédiatement le formulaire live via l’URL publique et le QR.',
      collectionStatusMissingCopy:
        'Aucun formulaire de feedback n’est actuellement rattaché à cet espace.',
      liveFormUrlEyebrow: 'URL du formulaire live',
      liveFormUrlTitle: 'Partager le parcours public de feedback',
      publicUrlLabel: 'URL publique',
      reviewChannelEyebrow: 'Canal d’avis',
      reviewChannelTitle: 'Destination Google Reviews',
      reviewChannelConnectedCopy:
        'Envoyez les clients vers une page d’avis externe après la fin du parcours de feedback.',
      reviewChannelMissingCopy:
        'Ajoutez un lien Google Reviews si vous voulez associer collecte privée et avis publics.',
      qrUtilityEyebrow: 'Utilitaire QR',
      qrUtilityTitle: 'Accès QR imprimable',
      qrUtilityCopy: 'Actualisez l’aperçu ou téléchargez un PNG sans quitter l’éditeur.',
      qrUtilityHint: 'Cliquez sur l’aperçu pour ouvrir une vue de scan plus grande.',
      questionBuilderTitle: 'Éditeur de questions',
      questionBuilderCopy:
        'Construisez et localisez le formulaire live avec un éditeur plus clair, pensé pour une revue rapide et une publication fiable.',
      builderEyebrow: 'Constructeur de formulaire',
      builderLeadTitle: 'Concevoir le parcours de questions que les clients noteront',
      builderLeadCopy:
        'Le français reste le libellé source obligatoire. L’arabe, l’anglais et l’espagnol peuvent être affinés avant publication, sans quitter cet espace.',
      newQuestionEyebrow: 'Nouvelle question',
      newQuestionTitle: 'Préparez le prochain intitulé avant de l’ajouter au brouillon',
      newQuestionCopy:
        'Rédigez le libellé principal une fois, puis affinez les versions localisées pour offrir un formulaire soigné dans chaque langue.',
      upToTenQuestions: 'Jusqu’à 10 questions au total',
      noQuestionsTitle: 'Aucune question configurée',
      noQuestionsCopy:
        'Commencez avec le composeur ci-dessus pour créer la première question multilingue du formulaire live.',
      frenchHelper: 'Libellé source live principal et champ obligatoire.',
      arabicHelper: 'Affiché aux clients arabophones et doit se lire naturellement en RTL.',
      englishHelper: 'Version localisée facultative pour les clients anglophones.',
      spanishHelper: 'Version localisée facultative pour les clients hispanophones.',
    },
    settings: {
      businessTitle: 'Paramètres de l’établissement',
      businessCopy: 'Informations cœur de l’espace utilisées dans toute l’expérience feedback.',
      businessName: 'Nom de l’établissement',
      plan: 'Plan',
      googleReviewUrl: 'URL Google Reviews',
      planStatus: 'Statut du plan',
      brandingTitle: 'Identité et espace',
      brandingCopy: 'Gardez l’espace d’administration soigné et aligné avec l’image de marque.',
      workspaceOwner: 'Propriétaire de l’espace',
      planGuidance: 'Recommandation de plan',
    },
  },
  es: {
    ...EN_DASHBOARD_COPY,
    sections: {
      overview: {
        label: 'Resumen',
        description: 'KPIs clave, alertas de servicio y una lectura rápida de la satisfacción.',
      },
      analytics: {
        label: 'Analítica',
        description: 'Tendencias, distribución de puntuaciones y análisis por pregunta.',
      },
      feedback: {
        label: 'Feedback',
        description: 'Busca, filtra e inspecciona cada respuesta del cliente en detalle.',
      },
      operations: {
        label: 'Operaciones',
        description: 'Seguimiento operativo, riesgos de servicio y prioridades del día a día.',
      },
      collection: {
        label: 'Captación',
        description: 'Acceso público al formulario, QR y gestión de preguntas.',
      },
      settings: {
        label: 'Configuración',
        description: 'Perfil del negocio, marca, plan y controles del espacio.',
      },
    },
    common: {
      ...EN_DASHBOARD_COPY.common,
      brandTagline: 'Espacio de feedback del cliente',
      open: 'Abrir',
      save: 'Guardar configuración',
      saveChanges: 'Guardar cambios',
      publishChanges: 'Publicar cambios',
      addQuestion: 'Agregar pregunta',
      downloadPng: 'Descargar PNG',
      refreshPreview: 'Actualizar',
      openForm: 'Abrir formulario',
      openLiveForm: 'Abrir formulario activo',
      copyFormLink: 'Copiar enlace del formulario',
      copiedLink: 'Enlace copiado',
      copyFailed: 'Error al copiar',
      openNavigation: 'Abrir navegación',
      closeNavigation: 'Cerrar navegación',
      collapseSidebar: 'Contraer barra lateral',
      expandSidebar: 'Expandir barra lateral',
      reportingRange: 'Rango del informe',
      trendResolution: 'Resolución de tendencia',
      analyticsTrendResolution: 'Resolución analítica',
      searchFeedback: 'Buscar feedback',
      filterFeedback: 'Filtrar feedback',
      sortFeedback: 'Ordenar feedback',
      searchPlaceholder: 'Buscar comentarios o nombres de preguntas',
      noData: 'Sin datos',
      noCategory: 'Sin categoría',
      noWrittenComment: 'Sin comentario escrito',
      noWrittenCommentLong: 'No se dejó ningún comentario escrito en esta respuesta.',
      noScore: 'Sin puntuación',
      positive: 'Positivo',
      neutral: 'Neutral',
      attention: 'Atención',
      status: 'Estado',
      weakestQuestion: 'Pregunta más débil',
      questionScores: 'Puntuaciones por pregunta',
      customerComment: 'Comentario del cliente',
      feedbackDetails: 'Detalle del feedback',
      closeFeedbackDetails: 'Cerrar detalle del feedback',
      submitted: 'Enviado',
      overallScoreSuffix: 'puntuación general',
      questionWord: 'Pregunta',
      newQuestion: 'Nueva pregunta',
      draftQuestion: 'Pregunta en borrador',
      frenchLabel: 'Etiqueta en francés',
      arabicLabel: 'Etiqueta en árabe',
      englishLabel: 'Etiqueta en inglés',
      spanishLabel: 'Etiqueta en español',
      required: 'Obligatorio',
      responseSingular: 'respuesta',
      responsePlural: 'respuestas',
      resultSingular: 'resultado',
      resultPlural: 'resultados',
      questionSingular: 'pregunta',
      questionPlural: 'preguntas',
      itemSingular: 'elemento',
      itemPlural: 'elementos',
      slotSingular: 'espacio',
      slotPlural: 'espacios',
      ratedAreaSingular: 'área evaluada',
      ratedAreaPlural: 'áreas evaluadas',
      languageLabelSingular: 'etiqueta de idioma completada',
      languageLabelPlural: 'etiquetas de idioma completadas',
      removeQuestion: 'Eliminar pregunta',
      moveUp: 'Subir',
      moveDown: 'Bajar',
      fromResponses: 'de',
      lastUpdated: 'Última actualización',
      publicAccess: 'Acceso público',
      ready: 'Listo',
      inactive: 'Inactivo',
      notConfigured: 'No configurado',
      optional: 'Opcional',
      connected: 'Conectado',
      generated: 'Generado',
      previewAvailable: 'Vista previa disponible',
      liveFormReady: 'Formulario activo listo',
      setupNeeded: 'Configuración pendiente',
      previousPeriodFlat: 'Sin cambios vs periodo anterior',
      previousPeriodSuffix: 'vs periodo anterior',
      pointsSuffix: ' pts',
      lowScoreShare: 'proporción de notas bajas',
      currentWindow: 'Ventana actual',
      activePeriods: 'Períodos activos',
      quietPeriods: 'Períodos sin actividad',
      peakVolume: 'Pico de volumen',
      bestRatedPeriod: 'Período mejor valorado',
      averageVolume: 'Volumen medio',
      latestPeriod: 'Último período',
      periodsInView: 'períodos visibles',
      noVolumeDataYet: 'Todavía no hay datos de volumen',
      noScoredPeriodsYet: 'Todavía no hay períodos con puntuación',
      noResponses: 'Sin respuestas',
      noResponsesLatestPeriod: 'No se registraron respuestas en el último período.',
      noPeakVolumeYet: 'El volumen aparecerá aquí cuando empiecen a llegar respuestas.',
      noScoredPeriodYet: 'Todavía no hay un período puntuado disponible.',
      averageResponsesAcrossPeriods:
        'Promedio de respuestas entre los períodos activos de la ventana seleccionada.',
      averageRatingWord: 'de media',
      busiestPeriodSuffix: 'en el período con más volumen',
      closeQrPreview: 'Cerrar vista previa del QR',
      qrPreviewTitle: 'Vista previa del QR',
      qrPreviewHeading: 'Escanea cómodamente el formulario activo',
      qrPreviewCopy:
        'Usa esta vista ampliada desde otro teléfono o dispositivo cuando necesites escanear rápido el formulario activo.',
      openBusinessPhotoPreview: 'Abrir vista ampliada de la foto del negocio',
      closeBusinessPhotoPreview: 'Cerrar vista ampliada de la foto',
      businessPhoto: 'Foto del negocio',
      businessPhotoCopy:
        'Usa esta vista ampliada para revisar cómodamente la foto cargada del negocio.',
      signedInUser: 'Usuario conectado',
      replacePhoto: 'Reemplazar foto',
      uploadPhoto: 'Subir foto',
      photoUploaded: 'Foto cargada',
      noPhotoYet: 'Todavía no hay foto',
      removePhoto: 'Eliminar foto',
      clickPhotoToEnlarge: 'Haz clic en la foto para ampliarla.',
      signOut: 'Cerrar sesión',
      tryAgain: 'Intentar de nuevo',
      dashboardLoadError: 'No se pudo cargar el dashboard',
      dashboardLoadErrorCopy:
        'Ocurrió un problema al preparar el espacio. Intenta de nuevo para recargar los datos más recientes.',
      noStructuredRatingsTitle: 'No hay calificaciones estructuradas',
      noStructuredRatingsCopy:
        'Esta respuesta solo contiene la puntuación general y cualquier comentario escrito.',
      photoRemoved: 'La foto del negocio se eliminó correctamente.',
      photoRemoveError: 'No se pudo eliminar la foto del negocio.',
      firstQuestionInLiveForm: 'Primera pregunta del formulario activo',
      positionPrefix: 'Posición',
      positionInLiveOrderSuffix: 'en el orden activo',
      unpublishedChanges: 'Cambios sin publicar',
      liveFormSynced: 'Formulario activo sincronizado',
      draftSyncedWithLiveForm: 'El borrador coincide con el formulario activo',
      changesWaitingToPublish: 'Hay cambios pendientes de publicación',
      configureInSettings: 'Configurar en Ajustes',
      openGoogleReviews: 'Abrir Google Reviews',
      formBuilderEyebrow: 'Constructor del formulario',
      languageCoverage: 'Cobertura de idiomas',
    },
    header: {
      eyebrow: 'Dashboard del espacio',
      updating: 'Actualizando la vista del espacio',
    },
    options: {
      resolutions: { day: 'Día', week: 'Semana', month: 'Mes' },
      feedbackFilters: {
        all: 'Todo',
        attention: 'Atención',
        positive: 'Positivo',
        commented: 'Con comentario',
      },
      feedbackSorts: {
        newest: 'Orden: más reciente',
        oldest: 'Orden: más antiguo',
        highest: 'Orden: mayor puntuación',
        lowest: 'Orden: menor puntuación',
      },
      planStatuses: {
        active: 'Activo',
        trial: 'Prueba',
        past_due: 'Pago vencido',
        suspended: 'Suspendido',
      },
    },
    notices: {
      settingsSaved: 'La configuración del negocio se actualizó correctamente.',
      settingsError: 'No se pudo guardar la configuración del negocio.',
      logoSaved: 'La foto del negocio se actualizó correctamente.',
      logoError: 'No se pudo subir la foto del negocio.',
      logoRemoved: 'La foto del negocio se eliminó correctamente.',
      logoRemoveError: 'No se pudo eliminar la foto del negocio.',
      questionLimit: 'El formulario puede tener hasta 10 preguntas.',
      frenchRequired: 'Se requiere una etiqueta en francés antes de agregar una nueva pregunta.',
      questionAdded: 'La pregunta se agregó al borrador.',
      keepOneQuestion: 'El formulario debe conservar al menos una pregunta.',
      noForm: 'Todavía no existe un formulario de feedback para este espacio.',
      publishNeedsQuestion: 'Agrega al menos una pregunta antes de publicar.',
      publishError: 'No se pudieron publicar las preguntas del formulario.',
      publishSuccess: 'Las preguntas del formulario activo se actualizaron correctamente.',
    },
    overview: {
      ...EN_DASHBOARD_COPY.overview,
      metrics: {
        averageRating: 'Puntuación media',
        averageRatingNote: 'Tendencia general de satisfacción en el rango seleccionado.',
        totalFeedback: 'Total de feedback',
        totalFeedbackNote: 'Todas las respuestas recibidas en el rango analizado.',
        satisfactionRate: 'Tasa de satisfacción',
        satisfactionRateNote: 'Porcentaje de respuestas con 4/5 o más.',
        negativeAlerts: 'Alertas negativas',
        negativeAlertsNote: 'Respuestas con baja puntuación que merecen revisión rápida.',
      },
      reportingPulseTitle: 'Pulso del periodo',
      reportingPulseCopy:
        'Lectura más ligera del ritmo de respuestas dentro de la ventana seleccionada, agrupada por resolución.',
      noFeedbackTitle: 'No hay feedback en este rango',
      noFeedbackCopy: 'Amplía el rango de fechas o espera nuevas respuestas para alimentar el dashboard.',
      watchlistTitle: 'Lista operativa',
      watchlistCopy: 'Las señales de servicio y experiencia más importantes para revisar ahora.',
      watchlistEmptyTitle: 'No hay problemas urgentes de servicio',
      watchlistEmptyCopy:
        'La ventana de datos actual se ve saludable. Los nuevos riesgos aparecerán aquí si cambia el feedback.',
      recentFeedbackTitle: 'Feedback reciente',
      recentFeedbackCopy: 'Últimas respuestas de clientes con acceso rápido a la revisión detallada.',
      recentFeedbackEmptyTitle: 'Todavía no hay feedback reciente',
      recentFeedbackEmptyCopy:
        'Cuando los clientes envíen feedback, las respuestas más recientes aparecerán aquí.',
      performanceSnapshotTitle: 'Resumen de rendimiento',
      performanceSnapshotCopy:
        'Resumen conciso de la salud del servicio, la calidad por categoría y la cobertura de comentarios.',
      strongestCategory: 'Categoría más fuerte',
      weakestCategory: 'Categoría más débil',
      commentCoverage: 'Cobertura de comentarios',
      feedbackMix: 'Distribución del feedback',
      noCategoryData: 'Todavía no hay datos por categoría',
      watchlistAttentionTitleSuffix: 'respuestas con baja puntuación requieren seguimiento',
      watchlistAttentionCopy:
        'Las puntuaciones por debajo de 3/5 indican oportunidades de recuperación del servicio que deben revisarse rápido.',
      watchlistWeakestTitleSuffix: 'es el área de servicio más débil',
      watchlistWeakestCopySuffix: 'de media con',
      watchlistWeakestCopyTail: 'en la ventana seleccionada.',
      watchlistDriftTitle: 'La puntuación media se está debilitando frente al periodo anterior',
      watchlistDriftCopyTail: 'Revisa los comentarios negativos más recientes para obtener contexto.',
      watchlistCommentTitle: 'Los comentarios escritos siguen siendo escasos',
      watchlistCommentCopyPrefix: 'Solo',
      watchlistCommentCopySuffix:
        'de los clientes dejaron contexto escrito, lo que limita el diagnóstico.',
    },
    analytics: {
      ...EN_DASHBOARD_COPY.analytics,
      ratingsTrendTitle: 'Tendencia de puntuaciones',
      ratingsTrendCopy:
        'Sigue el volumen de respuestas y la puntuación media en el tiempo por día, semana o mes.',
      trendEmptyTitle: 'La tendencia necesita datos recientes',
      trendEmptyCopy: 'No hay suficiente feedback en esta ventana para construir una tendencia fiable.',
      ratingsDistributionTitle: 'Distribución de puntuaciones',
      ratingsDistributionCopy: 'Desglose puntuación por puntuación de la experiencia general.',
      distributionEmptyTitle: 'Distribución no disponible',
      distributionEmptyCopy:
        'La distribución se vuelve útil cuando el rango seleccionado contiene feedback real.',
      sentimentMixAria: 'Mezcla de sentimiento del feedback',
      questionPerformanceTitle: 'Rendimiento por pregunta',
      questionPerformanceCopy:
        'Lectura pregunta por pregunta para identificar lo que valoran los clientes y dónde falla el servicio.',
      questionEmptyTitle: 'La analítica por pregunta necesita más datos',
      questionEmptyCopy:
        'Los insights por pregunta aparecerán en cuanto los clientes califiquen las preguntas activas.',
      recurringIssuesTitle: 'Problemas recurrentes',
      recurringIssuesCopy:
        'Categorías débiles que se repiten con suficiente frecuencia como para justificar una acción operativa.',
      recurringIssuesEmptyTitle: 'No hay un patrón recurrente',
      recurringIssuesEmptyCopy:
        'En cuanto una pregunta se convierta en un problema constante, se destacará aquí.',
      takeawaysTitle: 'Lecturas de tendencia',
      takeawaysCopy: 'Contexto sobre cuánta señal real existe en esta ventana analítica.',
    },
    feedback: {
      title: 'Lista de feedback',
      copy:
        'Busca comentarios, ordena por puntuación o fecha y abre el detalle completo en un panel lateral.',
      tableDate: 'Fecha',
      tableScore: 'Puntuación',
      tableWeakestArea: 'Área más débil',
      tableComment: 'Comentario',
      tableStatus: 'Estado',
      emptyTitle: 'Ningún feedback coincide con estos filtros',
      emptyCopy:
        'Prueba un rango más amplio o limpia la combinación activa de búsqueda, filtro y orden.',
    },
    operations: {
      currentLocationTitle: 'Resumen de la ubicación actual',
      currentLocationCopy:
        'Hoy el espacio representa una sola entidad de negocio, por lo que este panel funciona como una vista en vivo del lugar.',
      location: 'Ubicación',
      city: 'Ciudad',
      sector: 'Sector',
      latestFeedback: 'Último feedback',
      noFeedbackYet: 'Todavía no hay feedback',
      branchesTitle: 'Sucursales y ubicaciones',
      branchesCopy:
        'Preparado para analítica multiubicación sin ocultar los límites actuales del backend.',
      branchesEmptyTitle: 'La comparación entre sucursales aún no está disponible',
      branchesEmptyCopy:
        'El backend hoy almacena un solo espacio de negocio sin entidades de sucursal ni propiedad de respuestas por ubicación. Cuando existan esos modelos, esta zona podrá mostrar las mejores y peores ubicaciones.',
      serviceInsightsTitle: 'Insights de servicio',
      serviceInsightsCopy:
        'Lectura operativa de las categorías más débiles, incluso antes de contar con seguimiento por personal.',
      serviceInsightsEmptyTitle: 'No hay suficiente señal operativa',
      serviceInsightsEmptyCopy:
        'A medida que lleguen más respuestas, será más fácil separar los problemas reales del ruido.',
      checklistTitle: 'Checklist operativa',
      checklistCopy: 'Acciones sugeridas para managers según el estado actual del producto y los datos.',
      checklistLowScoreTitle: 'Revisar a diario el feedback con baja puntuación',
      checklistLowScoreNone:
        'No hay respuestas con baja puntuación apareciendo en esta ventana de reporte.',
      checklistLowScoreNeedsAttentionSuffix: 'siguen necesitando atención en la ventana seleccionada.',
      checklistFormTitle: 'Mantener el formulario activo alineado con la operación',
      checklistFormNone: 'Todavía no hay preguntas activas configuradas.',
      checklistFormConfiguredSuffix: 'impulsan actualmente la captación de feedback.',
      checklistCommentTitle: 'Mejorar el contexto escrito de los clientes',
      checklistCommentCoveragePrefix: 'La cobertura de comentarios escritos está en',
      checklistCommentGoodTail: 'lo que aporta más detalle cualitativo.',
      checklistCommentLowPrefix: 'La cobertura de comentarios escritos es solo de',
      checklistCommentLowTail:
        'así que el diagnóstico todavía depende mucho de los patrones de puntuación.',
      checklistDimensionsTitle: 'Preparar dimensiones de sucursal y personal',
      checklistDimensionsCopy:
        'Las vistas multiubicación y de personal requieren tablas backend para ubicaciones, personal y relaciones con las respuestas.',
    },
    collection: {
      distributionTitle: 'Distribución y QR',
      distributionCopy:
        'Mantén los activos de captación compactos, accesibles y fáciles de distribuir sin saturar el editor.',
      collectionStatusEyebrow: 'Estado de captación',
      feedbackFormAccessTitle: 'Acceso al formulario de feedback',
      collectionStatusReadyCopy:
        'Los clientes pueden abrir el formulario activo de inmediato desde la URL pública y el QR.',
      collectionStatusMissingCopy:
        'Actualmente no hay ningún formulario de feedback vinculado a este espacio.',
      liveFormUrlEyebrow: 'URL del formulario activo',
      liveFormUrlTitle: 'Compartir el flujo público de feedback',
      publicUrlLabel: 'URL pública',
      reviewChannelEyebrow: 'Canal de reseñas',
      reviewChannelTitle: 'Destino de Google Reviews',
      reviewChannelConnectedCopy:
        'Envía a los clientes a una página externa de reseñas después de completar el flujo de feedback.',
      reviewChannelMissingCopy:
        'Agrega un enlace de Google Reviews si quieres combinar la captación privada con reseñas públicas.',
      qrUtilityEyebrow: 'Utilidad QR',
      qrUtilityTitle: 'Acceso QR imprimible',
      qrUtilityCopy: 'Actualiza la vista previa o descarga un PNG sin salir del editor.',
      qrUtilityHint: 'Haz clic en la vista previa para abrir una vista de escaneo más grande.',
      questionBuilderTitle: 'Constructor de preguntas',
      questionBuilderCopy:
        'Construye y localiza el formulario activo con un editor más claro, pensado para revisar rápido y publicar con confianza.',
      builderEyebrow: 'Constructor del formulario',
      builderLeadTitle: 'Diseña el flujo de preguntas que el cliente va a calificar',
      builderLeadCopy:
        'El francés sigue siendo la etiqueta fuente obligatoria. El árabe, el inglés y el español pueden pulirse antes de publicar sin salir de este espacio.',
      newQuestionEyebrow: 'Nueva pregunta',
      newQuestionTitle: 'Redacta el siguiente prompt antes de añadirlo al borrador',
      newQuestionCopy:
        'Redacta el texto principal una sola vez y luego ajusta las versiones localizadas para que el formulario se vea pulido en todos los idiomas.',
      upToTenQuestions: 'Hasta 10 preguntas en total',
      noQuestionsTitle: 'No hay preguntas configuradas',
      noQuestionsCopy:
        'Empieza con el compositor de arriba para crear la primera pregunta multilingüe del formulario activo.',
      frenchHelper: 'Etiqueta principal del formulario activo y campo obligatorio.',
      arabicHelper: 'Visible para clientes arabófonos y debe leerse de forma natural en RTL.',
      englishHelper: 'Versión localizada opcional para clientes anglófonos.',
      spanishHelper: 'Versión localizada opcional para clientes hispanohablantes.',
    },
    settings: {
      businessTitle: 'Configuración del negocio',
      businessCopy: 'Datos principales del espacio usados en toda la experiencia de feedback.',
      businessName: 'Nombre del negocio',
      plan: 'Plan',
      googleReviewUrl: 'URL de Google Reviews',
      planStatus: 'Estado del plan',
      brandingTitle: 'Marca y espacio',
      brandingCopy: 'Mantén el espacio de administración pulido y alineado con la marca.',
      workspaceOwner: 'Propietario del espacio',
      planGuidance: 'Guía del plan',
    },
  },
  ar: {
    ...EN_DASHBOARD_COPY,
    sections: {
      overview: {
        label: 'نظرة عامة',
        description: 'مؤشرات أساسية، وتنبيهات الخدمة، وقراءة سريعة لمستوى رضا العملاء.',
      },
      analytics: {
        label: 'التحليلات',
        description: 'الاتجاهات، وتوزيع التقييمات، وتحليل الملاحظات حسب كل سؤال.',
      },
      feedback: {
        label: 'الملاحظات',
        description: 'ابحث وفلتر وراجع كل رد من العملاء بشكل مفصل.',
      },
      operations: {
        label: 'العمليات',
        description: 'متابعة التشغيل، ومخاطر الخدمة، وأولويات التنفيذ اليومي.',
      },
      collection: {
        label: 'جمع الملاحظات',
        description: 'الوصول العام إلى النموذج، ورمز QR، وإدارة الأسئلة.',
      },
      settings: {
        label: 'الإعدادات',
        description: 'ملف النشاط، والهوية، والخطة، وعناصر التحكم في مساحة العمل.',
      },
    },
    common: {
      ...EN_DASHBOARD_COPY.common,
      brandTagline: 'مساحة ملاحظات العملاء',
      open: 'فتح',
      save: 'حفظ الإعدادات',
      saveChanges: 'حفظ التغييرات',
      publishChanges: 'نشر التغييرات',
      addQuestion: 'إضافة سؤال',
      downloadPng: 'تنزيل PNG',
      refreshPreview: 'تحديث',
      openForm: 'فتح النموذج',
      openLiveForm: 'فتح النموذج المباشر',
      copyFormLink: 'نسخ رابط النموذج',
      copiedLink: 'تم نسخ الرابط',
      copyFailed: 'تعذر النسخ',
      openNavigation: 'فتح التنقل',
      closeNavigation: 'إغلاق التنقل',
      collapseSidebar: 'تصغير الشريط الجانبي',
      expandSidebar: 'توسيع الشريط الجانبي',
      reportingRange: 'فترة التقرير',
      trendResolution: 'مستوى الاتجاه',
      analyticsTrendResolution: 'مستوى الاتجاه في التحليلات',
      searchFeedback: 'البحث في الملاحظات',
      filterFeedback: 'تصفية الملاحظات',
      sortFeedback: 'ترتيب الملاحظات',
      searchPlaceholder: 'ابحث في التعليقات أو أسماء الأسئلة',
      noData: 'لا توجد بيانات',
      noCategory: 'بدون فئة',
      noWrittenComment: 'لا يوجد تعليق مكتوب',
      noWrittenCommentLong: 'لم يترك العميل تعليقاً مكتوباً في هذا الرد.',
      noScore: 'بدون تقييم',
      positive: 'إيجابي',
      neutral: 'محايد',
      attention: 'يحتاج متابعة',
      status: 'الحالة',
      weakestQuestion: 'أضعف سؤال',
      questionScores: 'درجات الأسئلة',
      customerComment: 'تعليق العميل',
      feedbackDetails: 'تفاصيل الملاحظة',
      closeFeedbackDetails: 'إغلاق تفاصيل الملاحظة',
      submitted: 'تاريخ الإرسال',
      overallScoreSuffix: 'التقييم العام',
      questionWord: 'السؤال',
      newQuestion: 'سؤال جديد',
      draftQuestion: 'سؤال في المسودة',
      frenchLabel: 'النص الفرنسي',
      arabicLabel: 'النص العربي',
      englishLabel: 'النص الإنجليزي',
      spanishLabel: 'النص الإسباني',
      required: 'إلزامي',
      responseSingular: 'رد',
      responsePlural: 'ردود',
      resultSingular: 'نتيجة',
      resultPlural: 'نتائج',
      questionSingular: 'سؤال',
      questionPlural: 'أسئلة',
      itemSingular: 'عنصر',
      itemPlural: 'عناصر',
      slotSingular: 'مكان',
      slotPlural: 'أماكن',
      ratedAreaSingular: 'عنصر مقيّم',
      ratedAreaPlural: 'عناصر مقيّمة',
      languageLabelSingular: 'تسمية لغة مكتملة',
      languageLabelPlural: 'تسميات لغات مكتملة',
      removeQuestion: 'حذف السؤال',
      moveUp: 'تحريك للأعلى',
      moveDown: 'تحريك للأسفل',
      fromResponses: 'من',
      lastUpdated: 'آخر تحديث',
      publicAccess: 'الوصول العام',
      ready: 'جاهز',
      inactive: 'غير نشط',
      notConfigured: 'غير مهيأ',
      optional: 'اختياري',
      connected: 'متصل',
      generated: 'تم التوليد',
      previewAvailable: 'المعاينة متاحة',
      liveFormReady: 'النموذج المباشر جاهز',
      setupNeeded: 'يلزم الإعداد',
      previousPeriodFlat: 'ثابت مقارنة بالفترة السابقة',
      previousPeriodSuffix: 'مقارنة بالفترة السابقة',
      pointsSuffix: ' نقطة',
      lowScoreShare: 'نسبة التقييمات المنخفضة',
      currentWindow: 'الفترة الحالية',
      activePeriods: 'الفترات النشطة',
      quietPeriods: 'الفترات الهادئة',
      peakVolume: 'ذروة الحجم',
      bestRatedPeriod: 'أفضل فترة من حيث التقييم',
      averageVolume: 'متوسط الحجم',
      latestPeriod: 'أحدث فترة',
      periodsInView: 'فترات معروضة',
      noVolumeDataYet: 'لا توجد بيانات حجم حتى الآن',
      noScoredPeriodsYet: 'لا توجد فترات مقيّمة حتى الآن',
      noResponses: 'لا توجد ردود',
      noResponsesLatestPeriod: 'لم تُسجَّل أي ردود في أحدث فترة.',
      noPeakVolumeYet: 'سيظهر الحجم هنا بمجرد وصول الردود.',
      noScoredPeriodYet: 'لا توجد فترة مقيّمة متاحة حتى الآن.',
      averageResponsesAcrossPeriods: 'متوسط عدد الردود عبر الفترات النشطة ضمن النافذة المحددة.',
      averageRatingWord: 'كمتوسط',
      busiestPeriodSuffix: 'في الفترة الأعلى حجماً',
      closeQrPreview: 'إغلاق معاينة QR',
      qrPreviewTitle: 'معاينة QR',
      qrPreviewHeading: 'امسح نموذج الملاحظات المباشر بسهولة أكبر',
      qrPreviewCopy:
        'استخدم هذه المعاينة المكبرة من هاتف أو جهاز آخر عندما تحتاج إلى مسح النموذج المباشر بسرعة.',
      openBusinessPhotoPreview: 'فتح المعاينة المكبرة لصورة النشاط',
      closeBusinessPhotoPreview: 'إغلاق معاينة صورة النشاط',
      businessPhoto: 'صورة النشاط',
      businessPhotoCopy: 'استخدم هذه المعاينة المكبرة لمراجعة صورة النشاط المرفوعة بشكل مريح.',
      signedInUser: 'المستخدم الحالي',
      replacePhoto: 'استبدال الصورة',
      uploadPhoto: 'رفع صورة',
      photoUploaded: 'تم رفع الصورة',
      noPhotoYet: 'لا توجد صورة بعد',
      removePhoto: 'إزالة الصورة',
      clickPhotoToEnlarge: 'انقر على الصورة لتكبيرها.',
      signOut: 'تسجيل الخروج',
      tryAgain: 'حاول مرة أخرى',
      dashboardLoadError: 'تعذر تحميل لوحة التحكم',
      dashboardLoadErrorCopy:
        'حدث خطأ أثناء تجهيز مساحة العمل. حاول مرة أخرى لإعادة تحميل أحدث البيانات.',
      noStructuredRatingsTitle: 'لا توجد تقييمات تفصيلية',
      noStructuredRatingsCopy:
        'يحتوي هذا الرد فقط على التقييم العام وأي تعليق مكتوب إن وُجد.',
      photoRemoved: 'تمت إزالة صورة النشاط بنجاح.',
      photoRemoveError: 'تعذر إزالة صورة النشاط.',
      firstQuestionInLiveForm: 'أول سؤال في النموذج المباشر',
      positionPrefix: 'الموضع',
      positionInLiveOrderSuffix: 'في الترتيب المباشر',
      unpublishedChanges: 'تغييرات غير منشورة',
      liveFormSynced: 'النموذج المباشر متزامن',
      draftSyncedWithLiveForm: 'المسودة مطابقة للنموذج المباشر',
      changesWaitingToPublish: 'هناك تغييرات بانتظار النشر',
      configureInSettings: 'قم بالإعداد من قسم الإعدادات',
      openGoogleReviews: 'فتح Google Reviews',
      formBuilderEyebrow: 'منشئ النموذج',
      languageCoverage: 'تغطية اللغات',
    },
    header: {
      eyebrow: 'لوحة مساحة العمل',
      updating: 'يتم تحديث العرض حالياً',
    },
    options: {
      resolutions: { day: 'يوم', week: 'أسبوع', month: 'شهر' },
      feedbackFilters: {
        all: 'الكل',
        attention: 'يحتاج متابعة',
        positive: 'إيجابي',
        commented: 'مع تعليق',
      },
      feedbackSorts: {
        newest: 'الترتيب: الأحدث',
        oldest: 'الترتيب: الأقدم',
        highest: 'الترتيب: الأعلى تقييماً',
        lowest: 'الترتيب: الأقل تقييماً',
      },
      planStatuses: {
        active: 'نشط',
        trial: 'تجريبي',
        past_due: 'متأخر في السداد',
        suspended: 'موقوف',
      },
    },
    notices: {
      settingsSaved: 'تم تحديث إعدادات النشاط بنجاح.',
      settingsError: 'تعذر حفظ إعدادات النشاط.',
      logoSaved: 'تم تحديث صورة النشاط بنجاح.',
      logoError: 'تعذر رفع صورة النشاط.',
      logoRemoved: 'تمت إزالة صورة النشاط بنجاح.',
      logoRemoveError: 'تعذر إزالة صورة النشاط.',
      questionLimit: 'يمكن أن يحتوي النموذج على 10 أسئلة كحد أقصى.',
      frenchRequired: 'يجب إدخال النص الفرنسي قبل إضافة سؤال جديد.',
      questionAdded: 'تمت إضافة السؤال إلى مسودة النموذج.',
      keepOneQuestion: 'يجب أن يحتفظ النموذج بسؤال واحد على الأقل.',
      noForm: 'لا يوجد نموذج ملاحظات لهذا النشاط حتى الآن.',
      publishNeedsQuestion: 'أضف سؤالاً واحداً على الأقل قبل النشر.',
      publishError: 'تعذر نشر أسئلة النموذج.',
      publishSuccess: 'تم تحديث أسئلة النموذج المباشر بنجاح.',
    },
    overview: {
      ...EN_DASHBOARD_COPY.overview,
      metrics: {
        averageRating: 'متوسط التقييم',
        averageRatingNote: 'اتجاه الرضا العام خلال فترة التقرير المحددة.',
        totalFeedback: 'إجمالي الملاحظات',
        totalFeedbackNote: 'جميع الردود المستلمة ضمن نافذة التقرير الحالية.',
        satisfactionRate: 'نسبة الرضا',
        satisfactionRateNote: 'نسبة الردود التي حصلت على 4/5 أو أكثر.',
        negativeAlerts: 'تنبيهات سلبية',
        negativeAlertsNote: 'الردود منخفضة التقييم التي تستحق مراجعة تشغيلية سريعة.',
      },
      reportingPulseTitle: 'نبض الفترة',
      reportingPulseCopy:
        'قراءة خفيفة لزخم الردود خلال النافذة المحددة، مع تجميعها حسب مستوى العرض.',
      noFeedbackTitle: 'لا توجد ملاحظات في هذه الفترة',
      noFeedbackCopy: 'وسّع الفترة الزمنية أو انتظر ردوداً جديدة لبدء ملء اللوحة.',
      watchlistTitle: 'قائمة المتابعة التشغيلية',
      watchlistCopy: 'أهم إشارات الخدمة والتجربة التي تستحق المراجعة الآن.',
      watchlistEmptyTitle: 'لا توجد مشكلات خدمة عاجلة',
      watchlistEmptyCopy:
        'نافذة البيانات الحالية تبدو مستقرة. ستظهر المخاطر الجديدة هنا عندما يتغير مستوى الملاحظات.',
      recentFeedbackTitle: 'أحدث الملاحظات',
      recentFeedbackCopy: 'أحدث ردود العملاء مع أسرع طريق إلى المراجعة التفصيلية.',
      recentFeedbackEmptyTitle: 'لا توجد ملاحظات حديثة بعد',
      recentFeedbackEmptyCopy:
        'بمجرد أن يرسل العملاء ملاحظاتهم، ستظهر أحدث الردود هنا.',
      performanceSnapshotTitle: 'ملخص الأداء',
      performanceSnapshotCopy:
        'قراءة مختصرة لصحة الخدمة، وجودة الفئات، ونسبة التعليقات المكتوبة.',
      strongestCategory: 'أفضل فئة',
      weakestCategory: 'أضعف فئة',
      commentCoverage: 'تغطية التعليقات',
      feedbackMix: 'توزيع الملاحظات',
      noCategoryData: 'لا توجد بيانات فئات حتى الآن',
      watchlistAttentionTitleSuffix: 'من الردود منخفضة التقييم تحتاج إلى متابعة',
      watchlistAttentionCopy:
        'الدرجات الأقل من 3/5 تشير إلى فرص لتحسين الخدمة ويجب مراجعتها بسرعة.',
      watchlistWeakestTitleSuffix: 'هي أضعف منطقة خدمة حالياً',
      watchlistWeakestCopySuffix: 'كمتوسط مع',
      watchlistWeakestCopyTail: 'خلال الفترة المحددة.',
      watchlistDriftTitle: 'متوسط التقييم يتراجع مقارنة بالفترة السابقة',
      watchlistDriftCopyTail: 'راجع أحدث التعليقات السلبية للحصول على السياق.',
      watchlistCommentTitle: 'التعليقات المكتوبة ما زالت محدودة',
      watchlistCommentCopyPrefix: 'فقط',
      watchlistCommentCopySuffix:
        'من العملاء تركوا تعليقاً مكتوباً، وهذا يحد من تشخيص المشكلات.',
    },
    analytics: {
      ...EN_DASHBOARD_COPY.analytics,
      ratingsTrendTitle: 'اتجاه التقييمات',
      ratingsTrendCopy:
        'تابع حجم الردود ومتوسط التقييم عبر الزمن حسب اليوم أو الأسبوع أو الشهر.',
      trendEmptyTitle: 'التحليلات تحتاج إلى بيانات أحدث',
      trendEmptyCopy: 'لا توجد ملاحظات كافية في هذه الفترة لبناء اتجاه موثوق.',
      ratingsDistributionTitle: 'توزيع التقييمات',
      ratingsDistributionCopy: 'تفصيل درجة بدرجة للتجربة العامة.',
      distributionEmptyTitle: 'التوزيع غير متاح',
      distributionEmptyCopy:
        'يصبح توزيع الدرجات مفيداً عندما تحتوي الفترة المحددة على ملاحظات حقيقية.',
      sentimentMixAria: 'توزيع مشاعر الملاحظات',
      questionPerformanceTitle: 'أداء الأسئلة',
      questionPerformanceCopy:
        'قراءة سؤال بسؤال لفهم ما يقدّره العملاء وأين تتراجع الخدمة.',
      questionEmptyTitle: 'تحليلات الأسئلة تحتاج إلى بيانات أكثر',
      questionEmptyCopy:
        'ستظهر الرؤى الخاصة بكل سؤال بمجرد أن يبدأ العملاء في تقييم أسئلة النموذج المباشر.',
      recurringIssuesTitle: 'المشكلات المتكررة',
      recurringIssuesCopy:
        'الفئات الضعيفة التي تتكرر بما يكفي لتستحق إجراءً تشغيلياً.',
      recurringIssuesEmptyTitle: 'لا يوجد نمط متكرر حالياً',
      recurringIssuesEmptyCopy:
        'عندما يتحول أحد الأسئلة إلى مشكلة مستمرة سيتم إبرازها هنا.',
      takeawaysTitle: 'خلاصات الاتجاه',
      takeawaysCopy: 'سياق يوضح حجم الإشارة المتاحة فعلياً داخل نافذة التحليل هذه.',
    },
    feedback: {
      title: 'قائمة الملاحظات',
      copy: 'ابحث في التعليقات، ورتب حسب الدرجة أو التاريخ، وافتح كل رد داخل لوحة جانبية.',
      tableDate: 'التاريخ',
      tableScore: 'الدرجة',
      tableWeakestArea: 'أضعف نقطة',
      tableComment: 'التعليق',
      tableStatus: 'الحالة',
      emptyTitle: 'لا توجد نتائج لهذه التصفية',
      emptyCopy:
        'جرّب فترة أوسع أو امسح البحث والتصفية والترتيب الحالي.',
    },
    operations: {
      currentLocationTitle: 'ملخص الموقع الحالي',
      currentLocationCopy:
        'في الوقت الحالي تمثل هذه المساحة نشاطاً واحداً فقط، لذلك يعمل هذا القسم كعرض مباشر للموقع.',
      location: 'الموقع',
      city: 'المدينة',
      sector: 'القطاع',
      latestFeedback: 'آخر ملاحظة',
      noFeedbackYet: 'لا توجد ملاحظات بعد',
      branchesTitle: 'الفروع والمواقع',
      branchesCopy:
        'جاهز لتحليلات متعددة المواقع مع الحفاظ على وضوح حدود الـ backend الحالية.',
      branchesEmptyTitle: 'مقارنة الفروع غير متاحة بعد',
      branchesEmptyCopy:
        'يحفظ الـ backend الحالي مساحة نشاط واحدة فقط دون كيانات للفروع أو ملكية للردود حسب الموقع. عند توفر هذه النماذج ستتمكن هذه المنطقة من عرض أفضل وأسوأ المواقع أداءً.',
      serviceInsightsTitle: 'رؤى الخدمة',
      serviceInsightsCopy:
        'قراءة تشغيلية للفئات الأضعف حتى قبل وجود تتبع على مستوى الموظفين.',
      serviceInsightsEmptyTitle: 'لا توجد إشارة تشغيلية كافية',
      serviceInsightsEmptyCopy:
        'كلما وصلت ردود أكثر أصبح من الأسهل فصل المشكلات الحقيقية عن الضوضاء.',
      checklistTitle: 'قائمة تشغيلية',
      checklistCopy: 'مهام مقترحة للمديرين بناءً على جاهزية المنتج والبيانات الحالية.',
      checklistLowScoreTitle: 'راجع الردود منخفضة التقييم يومياً',
      checklistLowScoreNone:
        'لا توجد حالياً ردود منخفضة التقييم ضمن نافذة التقرير هذه.',
      checklistLowScoreNeedsAttentionSuffix: 'ما زالت تحتاج إلى متابعة داخل الفترة المحددة.',
      checklistFormTitle: 'حافظ على توافق النموذج المباشر مع التشغيل',
      checklistFormNone: 'لا توجد أسئلة مباشرة مضبوطة حتى الآن.',
      checklistFormConfiguredSuffix: 'تقود حالياً جمع ملاحظات العملاء.',
      checklistCommentTitle: 'حسّن السياق المكتوب من الضيوف',
      checklistCommentCoveragePrefix: 'تغطية التعليقات المكتوبة وصلت إلى',
      checklistCommentGoodTail: 'وهذا يعطي تفاصيل نوعية أفضل.',
      checklistCommentLowPrefix: 'تغطية التعليقات المكتوبة لا تتجاوز',
      checklistCommentLowTail: 'لذلك ما زال التشخيص يعتمد بشكل كبير على نمط الدرجات.',
      checklistDimensionsTitle: 'جهّز بُعدي الفروع والموظفين',
      checklistDimensionsCopy:
        'عرض الفروع والموظفين يحتاج إلى جداول backend للمواقع والموظفين وربطها بالردود.',
    },
    collection: {
      distributionTitle: 'التوزيع ورمز QR',
      distributionCopy:
        'أبقِ أدوات التحصيل مدمجة وسهلة الوصول والتوزيع من دون أن تزدحم مساحة التحرير.',
      collectionStatusEyebrow: 'حالة التحصيل',
      feedbackFormAccessTitle: 'الوصول إلى نموذج الملاحظات',
      collectionStatusReadyCopy:
        'يمكن للضيوف فتح النموذج المباشر فوراً عبر الرابط العام ورمز QR.',
      collectionStatusMissingCopy: 'لا يوجد نموذج ملاحظات مرتبط بهذه المساحة حالياً.',
      liveFormUrlEyebrow: 'رابط النموذج المباشر',
      liveFormUrlTitle: 'مشاركة مسار الملاحظات العام',
      publicUrlLabel: 'الرابط العام',
      reviewChannelEyebrow: 'قناة المراجعات',
      reviewChannelTitle: 'وجهة Google Reviews',
      reviewChannelConnectedCopy:
        'وجّه العملاء إلى صفحة مراجعات خارجية بعد إكمال مسار الملاحظات.',
      reviewChannelMissingCopy:
        'أضف رابط Google Reviews إذا أردت الجمع بين الملاحظات الخاصة والمراجعات العامة.',
      qrUtilityEyebrow: 'أداة QR',
      qrUtilityTitle: 'وصول QR قابل للطباعة',
      qrUtilityCopy: 'حدّث المعاينة أو نزّل ملف PNG من دون مغادرة مساحة البناء.',
      qrUtilityHint: 'انقر على المعاينة لفتح عرض أكبر للمسح.',
      questionBuilderTitle: 'منشئ الأسئلة',
      questionBuilderCopy:
        'ابنِ النموذج المباشر ووفّر نسخه المحلية عبر محرر أوضح، مصمم للمراجعة السريعة والنشر بثقة.',
      builderEyebrow: 'منشئ النموذج',
      builderLeadTitle: 'صمّم مسار الأسئلة الذي سيقيّمه الضيوف',
      builderLeadCopy:
        'يبقى النص الفرنسي هو المصدر الإلزامي. ويمكن تحسين العربية والإنجليزية والإسبانية قبل النشر من داخل هذه المساحة.',
      newQuestionEyebrow: 'سؤال جديد',
      newQuestionTitle: 'صغ السؤال التالي قبل إضافته إلى المسودة',
      newQuestionCopy:
        'اكتب النص الرئيسي مرة واحدة، ثم حسّن النسخ المترجمة حتى يظهر النموذج بشكل احترافي في كل لغة.',
      upToTenQuestions: 'حتى 10 أسئلة كحد أقصى',
      noQuestionsTitle: 'لا توجد أسئلة مضبوطة',
      noQuestionsCopy:
        'ابدأ من أداة الإنشاء أعلاه لإنشاء أول سؤال متعدد اللغات في النموذج المباشر.',
      frenchHelper: 'النص الرئيسي للنموذج المباشر وهو حقل إلزامي.',
      arabicHelper: 'يظهر للضيوف الناطقين بالعربية ويجب أن يُقرأ بصورة طبيعية من اليمين إلى اليسار.',
      englishHelper: 'صياغة محلية اختيارية للضيوف الناطقين بالإنجليزية.',
      spanishHelper: 'صياغة محلية اختيارية للضيوف الناطقين بالإسبانية.',
    },
    settings: {
      businessTitle: 'إعدادات النشاط',
      businessCopy: 'بيانات مساحة العمل الأساسية المستخدمة في كامل تجربة الملاحظات.',
      businessName: 'اسم النشاط',
      plan: 'الخطة',
      googleReviewUrl: 'رابط Google Reviews',
      planStatus: 'حالة الخطة',
      brandingTitle: 'الهوية ومساحة العمل',
      brandingCopy: 'حافظ على مساحة الإدارة بشكل احترافي ومتسق مع هوية النشاط.',
      workspaceOwner: 'مالك المساحة',
      planGuidance: 'توجيه الخطة',
    },
  },
}
