import type { DashboardLang } from './dashboard-data'

export const DASHBOARD_LOCALES = {
  fr: 'fr-FR',
  ar: 'ar-MA',
  en: 'en-US',
  es: 'es-ES',
} as const

export function dashboardLocale(lang: DashboardLang) {
  return DASHBOARD_LOCALES[lang] || DASHBOARD_LOCALES.en
}

const EN_DASHBOARD_COPY = {
    sections: {
      overview: {
        label: 'Overview',
        description: 'Executive KPIs, service alerts, and a fast read on customer satisfaction.',
      },
      analytics: {
        label: 'Analytics',
        description: 'Trends, score distribution, and question-level feedback analysis.',
      },
      feedback: {
        label: 'Feedback',
        description: 'Search, filter, and inspect every customer submission in detail.',
      },
      operations: {
        label: 'Operations',
        description: 'Location readiness, service issues, and operational follow-up.',
      },
      collection: {
        label: 'Collection',
        description: 'Public form access, QR assets, and form question management.',
      },
      settings: {
        label: 'Settings',
        description: 'Business profile, branding, plan visibility, and workspace controls.',
      },
    },
    common: {
      brandTagline: 'Customer feedback workspace',
      dataLimitationsTitle: 'Data limitations',
      dataLimitationsCopy:
        'Branch and staff analytics remain placeholder-first until the backend exposes those entities explicitly.',
      open: 'Open',
      save: 'Save settings',
      saveChanges: 'Save changes',
      publishChanges: 'Publish changes',
      addQuestion: 'Add question',
      downloadPng: 'Download PNG',
      refreshPreview: 'Refresh preview',
      openForm: 'Open form',
      copyFormLink: 'Copy form link',
      copiedLink: 'Copied link',
      copyFailed: 'Copy failed',
      openNavigation: 'Open navigation',
      closeNavigation: 'Close navigation',
      collapseSidebar: 'Collapse sidebar',
      expandSidebar: 'Expand sidebar',
      reportingRange: 'Reporting range',
      trendResolution: 'Trend resolution',
      analyticsTrendResolution: 'Analytics trend resolution',
      searchFeedback: 'Search feedback',
      filterFeedback: 'Filter feedback',
      sortFeedback: 'Sort feedback',
      searchPlaceholder: 'Search comments or question names',
      noData: 'No data',
      noCategory: 'No category',
      noWrittenComment: 'No written comment',
      noWrittenCommentLong: 'No written comment was left on this response.',
      noScore: 'No score',
      positive: 'Positive',
      neutral: 'Neutral',
      attention: 'Attention',
      status: 'Status',
      weakestQuestion: 'Weakest question',
      questionScores: 'Question scores',
      customerComment: 'Customer comment',
      feedbackDetails: 'Feedback details',
      closeFeedbackDetails: 'Close feedback details',
      submitted: 'Submitted',
      overallScoreSuffix: 'overall score',
      questionWord: 'Question',
      newQuestion: 'New question',
      draftQuestion: 'Draft question',
      frenchLabel: 'French label',
      arabicLabel: 'Arabic label',
      englishLabel: 'English label',
      spanishLabel: 'Spanish label',
      responseSingular: 'response',
      responsePlural: 'responses',
      resultSingular: 'result',
      resultPlural: 'results',
      questionSingular: 'question',
      questionPlural: 'questions',
      itemSingular: 'item',
      itemPlural: 'items',
      ratedAreaSingular: 'rated area',
      ratedAreaPlural: 'rated areas',
      lastUpdated: 'Last updated',
      publicAccess: 'Public access',
      qrAvailability: 'QR availability',
      liveStatus: 'Live status',
      ready: 'Ready',
      needsAttention: 'Needs attention',
      inactive: 'Inactive',
      notConfigured: 'Not configured',
      lastDaysPrefix: 'Last',
      lastDaysSuffix: 'days',
      previousPeriodFlat: 'Flat vs previous period',
      previousPeriodSuffix: 'vs previous period',
      pointsSuffix: ' pts',
      lowScoreShare: 'low-score share',
      questionLimit: '10-question limit',
      signedInUser: 'Signed in user',
      replaceLogo: 'Replace logo',
      uploadLogo: 'Upload logo',
      logoUploaded: 'Logo uploaded',
      noLogoYet: 'No logo yet',
      signOut: 'Sign out',
      tryAgain: 'Try again',
      dashboardLoadError: 'Dashboard could not load',
      dashboardLoadErrorCopy:
        'Something went wrong while preparing the workspace. Try again to reload the latest data.',
      noStructuredRatingsTitle: 'No structured ratings',
      noStructuredRatingsCopy:
        'This feedback entry only contains the overall score and any written comment.',
    },
    header: {
      eyebrow: 'Workspace dashboard',
      updating: 'Updating workspace view',
    },
    options: {
      resolutions: {
        day: 'Day',
        week: 'Week',
        month: 'Month',
      },
      feedbackFilters: {
        all: 'All',
        attention: 'Attention',
        positive: 'Positive',
        commented: 'Commented',
      },
      feedbackSorts: {
        newest: 'Sort: Newest',
        oldest: 'Sort: Oldest',
        highest: 'Sort: Highest score',
        lowest: 'Sort: Lowest score',
      },
      planStatuses: {
        active: 'Active',
        trial: 'Trial',
        past_due: 'Past due',
        suspended: 'Suspended',
      },
    },
    notices: {
      settingsSaved: 'Business settings updated successfully.',
      settingsError: 'Could not save business settings.',
      logoSaved: 'Brand logo updated successfully.',
      logoError: 'Could not upload logo.',
      questionLimit: 'The form can contain up to 10 questions.',
      frenchRequired: 'A French label is required before adding a new question.',
      questionAdded: 'Question added to the draft form.',
      keepOneQuestion: 'The form must keep at least one question.',
      noForm: 'No feedback form exists for this workspace yet.',
      publishNeedsQuestion: 'Add at least one question before publishing.',
      publishError: 'Could not publish form questions.',
      publishSuccess: 'Live form questions updated successfully.',
    },
    overview: {
      metrics: {
        averageRating: 'Average rating',
        averageRatingNote: 'Overall satisfaction trend for the selected reporting window.',
        totalFeedback: 'Total feedback',
        totalFeedbackNote: 'Every submission received in the current reporting window.',
        satisfactionRate: 'Satisfaction rate',
        satisfactionRateNote: 'Share of responses scoring 4/5 or higher.',
        negativeAlerts: 'Negative alerts',
        negativeAlertsNote: 'Low-rating responses that deserve fast operational review.',
      },
      responseTrendTitle: 'Response trend',
      responseTrendCopy: 'Submission volume and average rating over the selected reporting window.',
      noFeedbackTitle: 'No feedback in this range',
      noFeedbackCopy: 'Widen the date range or wait for new responses to start filling the dashboard.',
      watchlistTitle: 'Operational watchlist',
      watchlistCopy: 'The most important service and experience signals to review right now.',
      watchlistEmptyTitle: 'No urgent service issues',
      watchlistEmptyCopy:
        'The current data window looks healthy. New risks will appear here as feedback changes.',
      recentFeedbackTitle: 'Recent feedback',
      recentFeedbackCopy: 'Latest customer responses with the fastest path into detailed review.',
      recentFeedbackEmptyTitle: 'No recent feedback yet',
      recentFeedbackEmptyCopy:
        'Once customers submit feedback, the latest responses will be surfaced here.',
      performanceSnapshotTitle: 'Performance snapshot',
      performanceSnapshotCopy:
        'A concise summary of service health, category quality, and comment coverage.',
      strongestCategory: 'Strongest category',
      weakestCategory: 'Weakest category',
      commentCoverage: 'Comment coverage',
      feedbackMix: 'Feedback mix',
      noCategoryData: 'No category data yet',
      watchlistAttentionCopy:
        'Scores below 3/5 signal service recovery opportunities that should be reviewed quickly.',
      watchlistWeakestTitleSuffix: 'is the weakest service area',
      watchlistWeakestCopySuffix: 'average with',
      watchlistWeakestCopyTail: 'in the selected window.',
      watchlistDriftTitle: 'Average rating is softening vs the previous period',
      watchlistDriftCopyTail: 'Review the most recent negative comments for context.',
      watchlistCommentTitle: 'Written comments are still sparse',
      watchlistCommentCopyPrefix: 'Only',
      watchlistCommentCopySuffix:
        'of customers left written context, which limits issue diagnosis.',
    },
    analytics: {
      ratingsTrendTitle: 'Ratings trend',
      ratingsTrendCopy: 'Track response volume and average score over time by day, week, or month.',
      trendEmptyTitle: 'Trend analytics need fresh data',
      trendEmptyCopy:
        'There is not enough feedback in the selected window to build a reliable trend.',
      ratingsDistributionTitle: 'Ratings distribution',
      ratingsDistributionCopy: 'A score-by-score breakdown of the overall rating experience.',
      distributionEmptyTitle: 'Distribution unavailable',
      distributionEmptyCopy:
        'Score distribution becomes useful once the selected date range contains real feedback.',
      sentimentMixAria: 'Feedback sentiment mix',
      questionPerformanceTitle: 'Question performance',
      questionPerformanceCopy:
        'Question-by-question scoring to pinpoint what customers value and where service slips.',
      questionEmptyTitle: 'Question analytics need more data',
      questionEmptyCopy:
        'Question-level insights will appear as soon as customers rate the live form questions.',
      recurringIssuesTitle: 'Recurring issues',
      recurringIssuesCopy:
        'Weak categories that are showing up often enough to deserve operational action.',
      recurringIssuesEmptyTitle: 'No recurring issue pattern',
      recurringIssuesEmptyCopy:
        'As soon as a question becomes a consistent problem, it will be highlighted here.',
      executiveSummaryTitle: 'Executive summary',
      executiveSummaryCopy: 'A compact view for weekly reporting and stakeholder check-ins.',
      averageRating: 'Average rating',
      feedbackCount: 'Feedback count',
      satisfactionRate: 'Satisfaction rate',
      currentWindow: 'Current window',
    },
    feedback: {
      title: 'Feedback list',
      copy: 'Search comments, sort by score or date, and open full submission details in a side drawer.',
      tableDate: 'Date',
      tableScore: 'Score',
      tableWeakestArea: 'Weakest area',
      tableComment: 'Comment',
      tableStatus: 'Status',
      emptyTitle: 'No feedback matches these filters',
      emptyCopy: 'Try a wider date range or clear the active search, filter, and sort combination.',
    },
    operations: {
      currentLocationTitle: 'Current location snapshot',
      currentLocationCopy:
        'Today the workspace maps to a single business entity, so this panel acts as the live location overview.',
      location: 'Location',
      city: 'City',
      sector: 'Sector',
      latestFeedback: 'Latest feedback',
      noFeedbackYet: 'No feedback yet',
      branchesTitle: 'Branches and locations',
      branchesCopy: 'Prepared for multi-location analytics, while staying honest about the current backend limits.',
      branchesEmptyTitle: 'Branch comparison is not available yet',
      branchesEmptyCopy:
        'The backend currently stores a single business workspace without branch entities or per-location submission ownership. Once those models exist, this area can show top and worst-performing locations.',
      serviceInsightsTitle: 'Service insights',
      serviceInsightsCopy:
        'Operational reading of the weakest categories, even before staff-level tracking exists.',
      serviceInsightsEmptyTitle: 'Not enough operational signal',
      serviceInsightsEmptyCopy:
        'As more responses arrive, service issues and recurring weak spots will be easier to separate from noise.',
      checklistTitle: 'Operational checklist',
      checklistCopy: 'Action prompts for managers based on current product and data readiness.',
      checklistLowScoreTitle: 'Review low-scoring feedback daily',
      checklistLowScoreNone:
        'No low-scoring submissions are currently surfacing in this reporting window.',
      checklistFormTitle: 'Keep the live form aligned with operations',
      checklistFormNone: 'No live questions are configured yet.',
      checklistCommentTitle: 'Improve written context from guests',
      checklistCommentGoodTail: 'which gives better qualitative detail.',
      checklistCommentLowTail:
        'so issue diagnosis still depends heavily on score patterns.',
      checklistDimensionsTitle: 'Prepare branch and staff dimensions',
      checklistDimensionsCopy:
        'Multi-branch and staff performance views need backend tables for locations, staff members, and submission relationships.',
    },
    collection: {
      overviewTitle: 'Collection overview',
      overviewCopy:
        'A live read on whether the public feedback flow, review routing, and form assets are ready for guests.',
      statusLiveForm: 'Live form',
      statusPublicAccess: 'Public access',
      statusQrAsset: 'QR asset',
      statusChannels: 'Channel readiness',
      statusLiveFormReady: 'Configured and ready to collect feedback.',
      statusLiveFormMissing: 'No feedback form is currently attached to this workspace.',
      statusPublicReady: 'Guests can open the live form immediately from the public URL.',
      statusPublicMissing: 'The public route exists, but the form still needs live questions to feel complete.',
      statusQrReady: 'QR generation is available for the current workspace.',
      statusQrMissing: 'QR has not yet been marked as generated in the current data model.',
      statusChannelsReady: 'Branding and destination links are ready for distribution.',
      statusChannelsMissing: 'Finish branding or add an external review destination before broad rollout.',
      distributionTitle: 'Distribution channels',
      distributionCopy:
        'Share the live form confidently across in-store assets, review flows, and customer touchpoints.',
      liveUrlTitle: 'Public form URL',
      liveUrlCopy: 'Primary guest-facing entry point for collecting direct feedback.',
      liveUrlHint: 'Use this link on receipts, kiosks, messages, or printed material.',
      reviewLinkTitle: 'Google review routing',
      reviewLinkCopy: 'Secondary destination for public review collection when a customer wants to post externally.',
      reviewLinkMissing: 'Add a Google review URL to complete the external review path.',
      reviewLinkHint: 'Keep the external destination current so QR and channel handoff stay trustworthy.',
      qrTitle: 'QR distribution asset',
      qrCopy: 'Download or refresh the printable QR code that points directly to the live form.',
      qrHint: 'Use a clean QR on counters, tables, packaging, and post-service touchpoints.',
      questionStudioTitle: 'Question management',
      questionStudioCopy:
        'Maintain the live question set with clearer structure, draft controls, and publishing discipline.',
      questionStudioMetricLive: 'Live questions',
      questionStudioMetricDraft: 'Draft status',
      questionStudioMetricCoverage: 'Language coverage',
      questionStudioMetricStatus: 'Collection status',
      questionStudioDraftClean: 'Draft matches the live form',
      questionStudioDraftPending: 'Draft changes are ready to publish',
      questionStudioCoverageReady: 'All guest-facing labels are covered',
      questionStudioCoveragePartial: 'Some translations still fall back to another language',
      questionStudioStatusReady: 'Publishing is available now',
      questionStudioStatusBlocked: 'A live form is required before publishing',
      questionStudioListTitle: 'Current draft set',
      questionStudioListCopy: 'Reorder, refine, and review the questions that shape structured feedback.',
      questionStudioComposerTitle: 'Add a new draft question',
      questionStudioComposerCopy:
        'Start with the French label, then complete the other languages so the public form stays consistent.',
      questionEmptyTitle: 'No questions configured',
      questionEmptyCopy:
        'Create the first question below to start collecting structured customer feedback.',
      brandingTitle: 'Branding and channels',
      brandingCopy:
        'Keep collection assets professional by aligning logo treatment and external destinations.',
      brandIdentityTitle: 'Brand identity',
      brandIdentityCopy: 'The logo shown on distribution assets should match what guests recognize instantly.',
      channelConfigTitle: 'Channel configuration',
      channelConfigCopy:
        'Control where customers land next and make sure public collection feels intentional across channels.',
      destinationLabel: 'Google review destination',
      destinationPlaceholder: 'https://...',
      destinationHint:
        'This link is reused in the distribution workspace and should point to the live review destination.',
      logoHint:
        'Upload a clean square logo for QR exports, printed materials, and public-facing collection touchpoints.',
      openDestination: 'Open destination',
    },
    settings: {
      businessTitle: 'Business settings',
      businessCopy: 'Core workspace details used across the feedback experience.',
      businessName: 'Business name',
      plan: 'Plan',
      googleReviewUrl: 'Google review URL',
      planStatus: 'Plan status',
      brandingTitle: 'Branding and workspace',
      brandingCopy: 'Keep the admin workspace polished and aligned with the business brand.',
      workspaceOwner: 'Workspace owner',
      planGuidance: 'Plan guidance',
    },
} as const

export const DASHBOARD_COPY = {
  en: EN_DASHBOARD_COPY,
  fr: {
    ...EN_DASHBOARD_COPY,
    sections: {
      overview: {
        label: 'Vue d ensemble',
        description: 'KPIs, alertes de service et lecture rapide de la satisfaction client.',
      },
      analytics: {
        label: 'Analytique',
        description: 'Tendances, repartition des notes et analyse du feedback par question.',
      },
      feedback: {
        label: 'Feedback',
        description: 'Recherchez, filtrez et ouvrez chaque reponse client en detail.',
      },
      operations: {
        label: 'Operations',
        description: 'Lecture des risques terrain, suivi service et readiness operationnelle.',
      },
      collection: {
        label: 'Collecte',
        description: 'Acces public au formulaire, QR et gestion des questions.',
      },
      settings: {
        label: 'Parametres',
        description: 'Profil business, branding, visibilite du plan et controles de l espace.',
      },
    },
    common: {
      ...EN_DASHBOARD_COPY.common,
      brandTagline: 'Espace de feedback client',
      dataLimitationsTitle: 'Limites de donnees',
      dataLimitationsCopy:
        'Les vues agences et staff restent en mode placeholder tant que le backend n expose pas ces entites.',
      open: 'Ouvrir',
      save: 'Enregistrer',
      saveChanges: 'Enregistrer',
      publishChanges: 'Publier les changements',
      addQuestion: 'Ajouter une question',
      downloadPng: 'Telecharger le PNG',
      refreshPreview: 'Actualiser l apercu',
      openForm: 'Ouvrir le formulaire',
      copyFormLink: 'Copier le lien du formulaire',
      copiedLink: 'Lien copie',
      copyFailed: 'Copie impossible',
      openNavigation: 'Ouvrir la navigation',
      closeNavigation: 'Fermer la navigation',
      collapseSidebar: 'Reduire la barre laterale',
      expandSidebar: 'Agrandir la barre laterale',
      reportingRange: 'Periode de reporting',
      trendResolution: 'Resolution de tendance',
      analyticsTrendResolution: 'Resolution de tendance analytique',
      searchFeedback: 'Rechercher dans le feedback',
      filterFeedback: 'Filtrer le feedback',
      sortFeedback: 'Trier le feedback',
      searchPlaceholder: 'Rechercher dans les commentaires ou les questions',
      noData: 'Pas de donnees',
      noCategory: 'Aucune categorie',
      noWrittenComment: 'Aucun commentaire ecrit',
      noWrittenCommentLong: 'Aucun commentaire ecrit n a ete laisse sur cette reponse.',
      noScore: 'Sans note',
      positive: 'Positif',
      neutral: 'Neutre',
      attention: 'A surveiller',
      status: 'Statut',
      weakestQuestion: 'Question la plus faible',
      questionScores: 'Scores par question',
      customerComment: 'Commentaire client',
      feedbackDetails: 'Details du feedback',
      closeFeedbackDetails: 'Fermer les details du feedback',
      submitted: 'Soumis',
      overallScoreSuffix: 'note globale',
      questionWord: 'Question',
      newQuestion: 'Nouvelle question',
      draftQuestion: 'Question brouillon',
      frenchLabel: 'Libelle francais',
      arabicLabel: 'Libelle arabe',
      englishLabel: 'Libelle anglais',
      spanishLabel: 'Libelle espagnol',
      responseSingular: 'reponse',
      responsePlural: 'reponses',
      resultSingular: 'resultat',
      resultPlural: 'resultats',
      questionSingular: 'question',
      questionPlural: 'questions',
      itemSingular: 'element',
      itemPlural: 'elements',
      ratedAreaSingular: 'zone notee',
      ratedAreaPlural: 'zones notees',
      lastUpdated: 'Derniere mise a jour',
      publicAccess: 'Acces public',
      qrAvailability: 'Disponibilite QR',
      liveStatus: 'Statut live',
      ready: 'Pret',
      needsAttention: 'A traiter',
      inactive: 'Inactif',
      notConfigured: 'Non configure',
      lastDaysPrefix: 'Derniers',
      lastDaysSuffix: 'jours',
      previousPeriodFlat: 'Stable vs periode precedente',
      previousPeriodSuffix: 'vs periode precedente',
      pointsSuffix: ' pts',
      lowScoreShare: 'part de notes basses',
      questionLimit: 'Limite de 10 questions',
      signedInUser: 'Utilisateur connecte',
      replaceLogo: 'Remplacer le logo',
      uploadLogo: 'Ajouter un logo',
      logoUploaded: 'Logo ajoute',
      noLogoYet: 'Pas encore de logo',
      signOut: 'Se deconnecter',
      tryAgain: 'Reessayer',
      dashboardLoadError: 'Le dashboard n a pas pu se charger',
      dashboardLoadErrorCopy:
        'Une erreur est survenue pendant la preparation de l espace. Reessayez pour recharger les donnees.',
      noStructuredRatingsTitle: 'Pas de notes detaillees',
      noStructuredRatingsCopy:
        'Cette reponse contient seulement la note globale et un eventuel commentaire ecrit.',
    },
    header: {
      eyebrow: 'Dashboard de l espace',
      updating: 'Mise a jour de la vue en cours',
    },
    options: {
      resolutions: { day: 'Jour', week: 'Semaine', month: 'Mois' },
      feedbackFilters: {
        all: 'Tout',
        attention: 'A surveiller',
        positive: 'Positif',
        commented: 'Avec commentaire',
      },
      feedbackSorts: {
        newest: 'Tri : plus recent',
        oldest: 'Tri : plus ancien',
        highest: 'Tri : meilleure note',
        lowest: 'Tri : note la plus basse',
      },
      planStatuses: {
        active: 'Actif',
        trial: 'Essai',
        past_due: 'Paiement en retard',
        suspended: 'Suspendu',
      },
    },
    notices: {
      settingsSaved: 'Les parametres business ont ete mis a jour.',
      settingsError: 'Impossible d enregistrer les parametres business.',
      logoSaved: 'Le logo de marque a ete mis a jour.',
      logoError: 'Impossible de telecharger le logo.',
      questionLimit: 'Le formulaire peut contenir jusqu a 10 questions.',
      frenchRequired: 'Un libelle francais est requis avant d ajouter une nouvelle question.',
      questionAdded: 'La question a ete ajoutee au brouillon du formulaire.',
      keepOneQuestion: 'Le formulaire doit conserver au moins une question.',
      noForm: 'Aucun formulaire de feedback n existe encore pour cet espace.',
      publishNeedsQuestion: 'Ajoutez au moins une question avant de publier.',
      publishError: 'Impossible de publier les questions du formulaire.',
      publishSuccess: 'Les questions live ont ete mises a jour avec succes.',
    },
    overview: {
      ...EN_DASHBOARD_COPY.overview,
      metrics: {
        averageRating: 'Note moyenne',
        averageRatingNote: 'Tendance globale de satisfaction sur la periode selectionnee.',
        totalFeedback: 'Total de feedback',
        totalFeedbackNote: 'Toutes les reponses recues dans la periode de reporting.',
        satisfactionRate: 'Taux de satisfaction',
        satisfactionRateNote: 'Part des reponses notees 4/5 ou plus.',
        negativeAlerts: 'Alertes negatives',
        negativeAlertsNote: 'Reponses a faible note qui meritent une revue rapide.',
      },
      responseTrendTitle: 'Tendance des reponses',
      responseTrendCopy: 'Volume des soumissions et note moyenne sur la periode selectionnee.',
      noFeedbackTitle: 'Aucun feedback sur cette periode',
      noFeedbackCopy: 'Elargissez la periode ou attendez de nouvelles reponses pour remplir le dashboard.',
      watchlistTitle: 'Watchlist operationnelle',
      watchlistCopy: 'Les signaux service et experience a revoir en priorite maintenant.',
      watchlistEmptyTitle: 'Aucun sujet urgent',
      watchlistEmptyCopy:
        'La fenetre de donnees actuelle semble saine. Les nouveaux risques apparaitront ici si le feedback change.',
      recentFeedbackTitle: 'Feedback recent',
      recentFeedbackCopy: 'Les dernieres reponses client avec le chemin le plus rapide vers le detail.',
      recentFeedbackEmptyTitle: 'Pas encore de feedback recent',
      recentFeedbackEmptyCopy:
        'Des que les clients soumettent du feedback, les dernieres reponses apparaissent ici.',
      performanceSnapshotTitle: 'Snapshot de performance',
      performanceSnapshotCopy:
        'Resume concis de la sante du service, de la qualite par categorie et de la couverture commentaire.',
      strongestCategory: 'Categorie la plus forte',
      weakestCategory: 'Categorie la plus faible',
      commentCoverage: 'Couverture commentaire',
      feedbackMix: 'Mix feedback',
      noCategoryData: 'Pas encore de donnees par categorie',
      watchlistAttentionCopy:
        'Les scores sous 3/5 signalent des opportunites de recovery a revoir rapidement.',
      watchlistWeakestTitleSuffix: 'est la zone de service la plus faible',
      watchlistWeakestCopySuffix: 'de moyenne avec',
      watchlistWeakestCopyTail: 'sur la periode selectionnee.',
      watchlistDriftTitle: 'La note moyenne baisse vs la periode precedente',
      watchlistDriftCopyTail: 'Consultez les derniers commentaires negatifs pour le contexte.',
      watchlistCommentTitle: 'Les commentaires ecrits restent rares',
      watchlistCommentCopyPrefix: 'Seulement',
      watchlistCommentCopySuffix:
        'des clients ont laisse un commentaire ecrit, ce qui limite le diagnostic.',
    },
    analytics: {
      ...EN_DASHBOARD_COPY.analytics,
      ratingsTrendTitle: 'Tendance des notes',
      ratingsTrendCopy:
        'Suivez le volume de reponses et la note moyenne par jour, semaine ou mois.',
      trendEmptyTitle: 'Les tendances ont besoin de donnees recentes',
      trendEmptyCopy: 'Il n y a pas assez de feedback sur cette fenetre pour une tendance fiable.',
      ratingsDistributionTitle: 'Repartition des notes',
      ratingsDistributionCopy: 'Vue score par score de l experience globale de notation.',
      distributionEmptyTitle: 'Repartition indisponible',
      distributionEmptyCopy:
        'La repartition des notes devient utile des que la plage de dates contient du vrai feedback.',
      sentimentMixAria: 'Mix de sentiment du feedback',
      questionPerformanceTitle: 'Performance par question',
      questionPerformanceCopy:
        'Lecture question par question pour voir ce que les clients apprecient et ou le service glisse.',
      questionEmptyTitle: 'Les analytiques par question ont besoin de plus de donnees',
      questionEmptyCopy:
        'Les insights par question apparaitront des que les clients noteront les questions live.',
      recurringIssuesTitle: 'Problemes recurrents',
      recurringIssuesCopy:
        'Les categories faibles qui reviennent assez souvent pour justifier une action operationnelle.',
      recurringIssuesEmptyTitle: 'Aucun schema recurrent',
      recurringIssuesEmptyCopy:
        'Des qu une question devient un probleme regulier, elle sera mise en avant ici.',
      executiveSummaryTitle: 'Resume executif',
      executiveSummaryCopy: 'Vue compacte pour les points hebdomadaires et les reportings stakeholders.',
      averageRating: 'Note moyenne',
      feedbackCount: 'Volume de feedback',
      satisfactionRate: 'Taux de satisfaction',
      currentWindow: 'Fenetre actuelle',
    },
    feedback: {
      title: 'Liste de feedback',
      copy: 'Recherchez les commentaires, triez par note ou date, et ouvrez le detail dans un panneau lateral.',
      tableDate: 'Date',
      tableScore: 'Score',
      tableWeakestArea: 'Zone la plus faible',
      tableComment: 'Commentaire',
      tableStatus: 'Statut',
      emptyTitle: 'Aucun feedback ne correspond aux filtres',
      emptyCopy:
        'Essayez une periode plus large ou videz la combinaison actuelle recherche, filtre et tri.',
    },
    operations: {
      currentLocationTitle: 'Snapshot du site actuel',
      currentLocationCopy:
        'Aujourd hui l espace correspond a une seule entite business, donc ce panneau sert de vue live du site.',
      location: 'Site',
      city: 'Ville',
      sector: 'Secteur',
      latestFeedback: 'Dernier feedback',
      noFeedbackYet: 'Pas encore de feedback',
      branchesTitle: 'Agences et sites',
      branchesCopy:
        'Pret pour l analytique multi-sites, tout en restant honnete sur les limites actuelles du backend.',
      branchesEmptyTitle: 'La comparaison de sites n est pas encore disponible',
      branchesEmptyCopy:
        'Le backend stocke aujourd hui un seul espace business sans entites agence ni proprietaire de soumission par site.',
      serviceInsightsTitle: 'Insights service',
      serviceInsightsCopy:
        'Lecture operationnelle des categories les plus faibles, meme sans suivi staff detaille.',
      serviceInsightsEmptyTitle: 'Pas assez de signal operationnel',
      serviceInsightsEmptyCopy:
        'A mesure que plus de reponses arrivent, il sera plus facile de separer les vrais problemes du bruit.',
      checklistTitle: 'Checklist operationnelle',
      checklistCopy: 'Prompts d action pour les managers selon l etat du produit et des donnees.',
      checklistLowScoreTitle: 'Revoir chaque jour les feedbacks a faible note',
      checklistLowScoreNone:
        'Aucune soumission a faible note ne ressort actuellement sur cette fenetre de reporting.',
      checklistFormTitle: 'Garder le formulaire live aligne avec l operationnel',
      checklistFormNone: 'Aucune question live n est configuree pour le moment.',
      checklistCommentTitle: 'Renforcer le contexte ecrit des clients',
      checklistCommentGoodTail: 'ce qui donne plus de detail qualitatif.',
      checklistCommentLowTail:
        'donc le diagnostic depend encore beaucoup des patterns de notes.',
      checklistDimensionsTitle: 'Preparer les dimensions agence et staff',
      checklistDimensionsCopy:
        'Les vues multi-sites et staff demandent des tables backend pour les sites, les employes et les relations de soumission.',
    },
    collection: {
      overviewTitle: 'Vue d ensemble de la collecte',
      overviewCopy:
        'Lecture live de la readiness du formulaire public, du routage review et des assets de collecte.',
      statusLiveForm: 'Formulaire live',
      statusPublicAccess: 'Acces public',
      statusQrAsset: 'Asset QR',
      statusChannels: 'Readiness canaux',
      statusLiveFormReady: 'Configure et pret a collecter du feedback.',
      statusLiveFormMissing: 'Aucun formulaire de feedback n est actuellement attache a cet espace.',
      statusPublicReady: 'Les clients peuvent ouvrir le formulaire live immediatement depuis l URL publique.',
      statusPublicMissing:
        'La route publique existe, mais le formulaire a encore besoin de questions live pour etre complet.',
      statusQrReady: 'La generation QR est disponible pour cet espace.',
      statusQrMissing: 'Le QR n a pas encore ete marque comme genere dans le modele actuel.',
      statusChannelsReady: 'Le branding et les liens de destination sont prets pour la distribution.',
      statusChannelsMissing:
        'Terminez le branding ou ajoutez une destination review externe avant un deploiement large.',
      distributionTitle: 'Canaux de distribution',
      distributionCopy:
        'Diffusez le formulaire live sereinement sur les supports en magasin, les flux review et les points de contact client.',
      liveUrlTitle: 'URL du formulaire public',
      liveUrlCopy: 'Point d entree principal cote client pour la collecte directe de feedback.',
      liveUrlHint: 'Utilisez ce lien sur les tickets, kiosques, messages ou supports imprimes.',
      reviewLinkTitle: 'Routage Google review',
      reviewLinkCopy:
        'Destination secondaire pour la collecte d avis publics quand un client veut publier en externe.',
      reviewLinkMissing: 'Ajoutez une URL Google review pour completer le parcours d avis externe.',
      reviewLinkHint: 'Gardez cette destination a jour pour que le handoff QR et canal reste fiable.',
      qrTitle: 'Asset QR de distribution',
      qrCopy: 'Telechargez ou actualisez le QR imprimable qui pointe directement vers le formulaire live.',
      qrHint: 'Utilisez un QR propre sur les comptoirs, tables, emballages et points de contact post-service.',
      questionStudioTitle: 'Gestion des questions',
      questionStudioCopy:
        'Maintenez le set de questions live avec une structure plus claire, des controles de brouillon et une publication propre.',
      questionStudioMetricLive: 'Questions live',
      questionStudioMetricDraft: 'Statut du brouillon',
      questionStudioMetricCoverage: 'Couverture langues',
      questionStudioMetricStatus: 'Statut de collecte',
      questionStudioDraftClean: 'Le brouillon correspond au live',
      questionStudioDraftPending: 'Les changements du brouillon sont prets a etre publies',
      questionStudioCoverageReady: 'Tous les libelles publics sont couverts',
      questionStudioCoveragePartial:
        'Certaines traductions retombent encore sur une autre langue',
      questionStudioStatusReady: 'La publication est disponible maintenant',
      questionStudioStatusBlocked: 'Un formulaire live est requis avant publication',
      questionStudioListTitle: 'Brouillon actuel',
      questionStudioListCopy: 'Reordonnez, ajustez et relisez les questions qui structurent le feedback.',
      questionStudioComposerTitle: 'Ajouter une nouvelle question brouillon',
      questionStudioComposerCopy:
        'Commencez par le libelle francais, puis completez les autres langues pour garder le formulaire coherent.',
      questionEmptyTitle: 'Aucune question configuree',
      questionEmptyCopy:
        'Creez la premiere question ci-dessous pour commencer a collecter un feedback structure.',
      brandingTitle: 'Branding et canaux',
      brandingCopy:
        'Gardez les assets de collecte professionnels en alignant le logo et les destinations externes.',
      brandIdentityTitle: 'Identite de marque',
      brandIdentityCopy:
        'Le logo affiche sur les supports de distribution doit correspondre a ce que les clients reconnaissent tout de suite.',
      channelConfigTitle: 'Configuration des canaux',
      channelConfigCopy:
        'Controlez ou les clients atterrissent ensuite et gardez une collecte publique claire sur chaque canal.',
      destinationLabel: 'Destination Google review',
      destinationPlaceholder: 'https://...',
      destinationHint:
        'Ce lien est reutilise dans l espace distribution et doit pointer vers la destination live.',
      logoHint:
        'Ajoutez un logo carre propre pour les exports QR, les supports imprimes et la collecte publique.',
      openDestination: 'Ouvrir la destination',
    },
    settings: {
      businessTitle: 'Parametres business',
      businessCopy: 'Informations coeur de l espace utilisees dans toute l experience feedback.',
      businessName: 'Nom du business',
      plan: 'Plan',
      googleReviewUrl: 'URL Google review',
      planStatus: 'Statut du plan',
      brandingTitle: 'Branding et espace',
      brandingCopy: 'Gardez l espace admin propre et aligne avec la marque.',
      workspaceOwner: 'Proprietaire de l espace',
      planGuidance: 'Guidance du plan',
    },
  },
  es: {
    ...EN_DASHBOARD_COPY,
    sections: {
      overview: {
        label: 'Resumen',
        description: 'KPIs clave, alertas de servicio y una lectura rapida de la satisfaccion.',
      },
      analytics: {
        label: 'Analitica',
        description: 'Tendencias, distribucion de puntuaciones y analisis por pregunta.',
      },
      feedback: {
        label: 'Feedback',
        description: 'Busca, filtra e inspecciona cada respuesta del cliente en detalle.',
      },
      operations: {
        label: 'Operaciones',
        description: 'Rendimiento operativo, riesgos de servicio y seguimiento.',
      },
      collection: {
        label: 'Captacion',
        description: 'Acceso publico al formulario, QR y gestion de preguntas.',
      },
      settings: {
        label: 'Configuracion',
        description: 'Perfil del negocio, marca, visibilidad del plan y controles del espacio.',
      },
    },
    common: {
      ...EN_DASHBOARD_COPY.common,
      brandTagline: 'Espacio de feedback del cliente',
      dataLimitationsTitle: 'Limites de datos',
      dataLimitationsCopy:
        'Las vistas de sucursales y personal siguen en modo placeholder hasta que el backend exponga esas entidades.',
      open: 'Abrir',
      save: 'Guardar',
      saveChanges: 'Guardar cambios',
      publishChanges: 'Publicar cambios',
      addQuestion: 'Agregar pregunta',
      downloadPng: 'Descargar PNG',
      refreshPreview: 'Actualizar vista previa',
      openForm: 'Abrir formulario',
      copyFormLink: 'Copiar enlace del formulario',
      copiedLink: 'Enlace copiado',
      copyFailed: 'Error al copiar',
      openNavigation: 'Abrir navegacion',
      closeNavigation: 'Cerrar navegacion',
      collapseSidebar: 'Colapsar barra lateral',
      expandSidebar: 'Expandir barra lateral',
      reportingRange: 'Rango de reporte',
      trendResolution: 'Resolucion de tendencia',
      analyticsTrendResolution: 'Resolucion de tendencia analitica',
      searchFeedback: 'Buscar feedback',
      filterFeedback: 'Filtrar feedback',
      sortFeedback: 'Ordenar feedback',
      searchPlaceholder: 'Buscar comentarios o nombres de preguntas',
      noData: 'Sin datos',
      noCategory: 'Sin categoria',
      noWrittenComment: 'Sin comentario escrito',
      noWrittenCommentLong: 'No se dejo un comentario escrito en esta respuesta.',
      noScore: 'Sin puntuacion',
      positive: 'Positivo',
      neutral: 'Neutral',
      attention: 'Atencion',
      status: 'Estado',
      weakestQuestion: 'Pregunta mas debil',
      questionScores: 'Puntuaciones por pregunta',
      customerComment: 'Comentario del cliente',
      feedbackDetails: 'Detalle del feedback',
      closeFeedbackDetails: 'Cerrar detalle del feedback',
      submitted: 'Enviado',
      overallScoreSuffix: 'puntuacion general',
      questionWord: 'Pregunta',
      newQuestion: 'Nueva pregunta',
      draftQuestion: 'Pregunta en borrador',
      frenchLabel: 'Etiqueta en frances',
      arabicLabel: 'Etiqueta en arabe',
      englishLabel: 'Etiqueta en ingles',
      spanishLabel: 'Etiqueta en espanol',
      responseSingular: 'respuesta',
      responsePlural: 'respuestas',
      resultSingular: 'resultado',
      resultPlural: 'resultados',
      questionSingular: 'pregunta',
      questionPlural: 'preguntas',
      itemSingular: 'elemento',
      itemPlural: 'elementos',
      ratedAreaSingular: 'area evaluada',
      ratedAreaPlural: 'areas evaluadas',
      lastUpdated: 'Ultima actualizacion',
      publicAccess: 'Acceso publico',
      qrAvailability: 'Disponibilidad QR',
      liveStatus: 'Estado en vivo',
      ready: 'Listo',
      needsAttention: 'Requiere atencion',
      inactive: 'Inactivo',
      notConfigured: 'No configurado',
      lastDaysPrefix: 'Ultimos',
      lastDaysSuffix: 'dias',
      previousPeriodFlat: 'Sin cambio vs periodo anterior',
      previousPeriodSuffix: 'vs periodo anterior',
      pointsSuffix: ' pts',
      lowScoreShare: 'proporcion de notas bajas',
      questionLimit: 'Limite de 10 preguntas',
      signedInUser: 'Usuario conectado',
      replaceLogo: 'Reemplazar logo',
      uploadLogo: 'Subir logo',
      logoUploaded: 'Logo cargado',
      noLogoYet: 'Sin logo aun',
      signOut: 'Cerrar sesion',
      tryAgain: 'Intentar de nuevo',
      dashboardLoadError: 'No se pudo cargar el dashboard',
      dashboardLoadErrorCopy:
        'Algo salio mal al preparar el espacio. Intenta de nuevo para recargar los datos.',
      noStructuredRatingsTitle: 'Sin calificaciones estructuradas',
      noStructuredRatingsCopy:
        'Esta respuesta solo contiene la puntuacion general y cualquier comentario escrito.',
    },
    header: {
      eyebrow: 'Dashboard del espacio',
      updating: 'Actualizando la vista del espacio',
    },
    options: {
      resolutions: { day: 'Dia', week: 'Semana', month: 'Mes' },
      feedbackFilters: {
        all: 'Todo',
        attention: 'Atencion',
        positive: 'Positivo',
        commented: 'Con comentario',
      },
      feedbackSorts: {
        newest: 'Orden: mas reciente',
        oldest: 'Orden: mas antiguo',
        highest: 'Orden: mayor puntuacion',
        lowest: 'Orden: menor puntuacion',
      },
      planStatuses: {
        active: 'Activo',
        trial: 'Prueba',
        past_due: 'Pago vencido',
        suspended: 'Suspendido',
      },
    },
    notices: {
      settingsSaved: 'La configuracion del negocio se actualizo correctamente.',
      settingsError: 'No se pudo guardar la configuracion del negocio.',
      logoSaved: 'El logo de marca se actualizo correctamente.',
      logoError: 'No se pudo subir el logo.',
      questionLimit: 'El formulario puede tener hasta 10 preguntas.',
      frenchRequired: 'Se requiere una etiqueta en frances antes de agregar una nueva pregunta.',
      questionAdded: 'La pregunta se agrego al borrador del formulario.',
      keepOneQuestion: 'El formulario debe mantener al menos una pregunta.',
      noForm: 'Todavia no existe un formulario de feedback para este espacio.',
      publishNeedsQuestion: 'Agrega al menos una pregunta antes de publicar.',
      publishError: 'No se pudieron publicar las preguntas del formulario.',
      publishSuccess: 'Las preguntas del formulario en vivo se actualizaron correctamente.',
    },
    overview: {
      ...EN_DASHBOARD_COPY.overview,
      metrics: {
        averageRating: 'Puntuacion media',
        averageRatingNote: 'Tendencia general de satisfaccion en el rango seleccionado.',
        totalFeedback: 'Total de feedback',
        totalFeedbackNote: 'Todas las respuestas recibidas en el rango actual.',
        satisfactionRate: 'Tasa de satisfaccion',
        satisfactionRateNote: 'Porcentaje de respuestas con 4/5 o mas.',
        negativeAlerts: 'Alertas negativas',
        negativeAlertsNote: 'Respuestas con baja puntuacion que merecen revision rapida.',
      },
      responseTrendTitle: 'Tendencia de respuestas',
      responseTrendCopy: 'Volumen de envios y puntuacion media en el rango seleccionado.',
      noFeedbackTitle: 'No hay feedback en este rango',
      noFeedbackCopy: 'Amplia el rango de fechas o espera nuevas respuestas para llenar el dashboard.',
      watchlistTitle: 'Lista operativa',
      watchlistCopy: 'Las senales de servicio y experiencia mas importantes para revisar ahora.',
      watchlistEmptyTitle: 'No hay problemas urgentes',
      watchlistEmptyCopy:
        'La ventana de datos actual se ve saludable. Los nuevos riesgos apareceran aqui si cambia el feedback.',
      recentFeedbackTitle: 'Feedback reciente',
      recentFeedbackCopy: 'Ultimas respuestas de clientes con acceso rapido a la revision detallada.',
      recentFeedbackEmptyTitle: 'Todavia no hay feedback reciente',
      recentFeedbackEmptyCopy:
        'Cuando los clientes envien feedback, las respuestas mas recientes apareceran aqui.',
      performanceSnapshotTitle: 'Resumen de rendimiento',
      performanceSnapshotCopy:
        'Resumen conciso de salud del servicio, calidad por categoria y cobertura de comentarios.',
      strongestCategory: 'Categoria mas fuerte',
      weakestCategory: 'Categoria mas debil',
      commentCoverage: 'Cobertura de comentarios',
      feedbackMix: 'Mezcla de feedback',
      noCategoryData: 'Todavia no hay datos por categoria',
      watchlistAttentionCopy:
        'Las puntuaciones por debajo de 3/5 indican oportunidades de recuperacion del servicio.',
      watchlistWeakestTitleSuffix: 'es el area de servicio mas debil',
      watchlistWeakestCopySuffix: 'de media con',
      watchlistWeakestCopyTail: 'en la ventana seleccionada.',
      watchlistDriftTitle: 'La puntuacion media se esta debilitando vs el periodo anterior',
      watchlistDriftCopyTail: 'Revisa los comentarios negativos mas recientes para tener contexto.',
      watchlistCommentTitle: 'Los comentarios escritos siguen siendo escasos',
      watchlistCommentCopyPrefix: 'Solo',
      watchlistCommentCopySuffix:
        'de los clientes dejaron contexto escrito, lo que limita el diagnostico.',
    },
    analytics: {
      ...EN_DASHBOARD_COPY.analytics,
      ratingsTrendTitle: 'Tendencia de puntuaciones',
      ratingsTrendCopy:
        'Sigue el volumen de respuestas y la puntuacion media por dia, semana o mes.',
      trendEmptyTitle: 'La tendencia necesita datos recientes',
      trendEmptyCopy: 'No hay suficiente feedback en esta ventana para construir una tendencia fiable.',
      ratingsDistributionTitle: 'Distribucion de puntuaciones',
      ratingsDistributionCopy: 'Desglose puntuacion por puntuacion de la experiencia general.',
      distributionEmptyTitle: 'Distribucion no disponible',
      distributionEmptyCopy:
        'La distribucion de puntuaciones se vuelve util cuando el rango seleccionado contiene feedback real.',
      sentimentMixAria: 'Mezcla de sentimiento del feedback',
      questionPerformanceTitle: 'Rendimiento por pregunta',
      questionPerformanceCopy:
        'Lectura pregunta por pregunta para ver que valoran los clientes y donde falla el servicio.',
      questionEmptyTitle: 'La analitica por pregunta necesita mas datos',
      questionEmptyCopy:
        'Los insights por pregunta apareceran en cuanto los clientes califiquen las preguntas activas.',
      recurringIssuesTitle: 'Problemas recurrentes',
      recurringIssuesCopy:
        'Categorias debiles que aparecen con suficiente frecuencia como para exigir accion.',
      recurringIssuesEmptyTitle: 'No hay patron recurrente',
      recurringIssuesEmptyCopy:
        'En cuanto una pregunta se convierta en un problema constante, se resaltara aqui.',
      executiveSummaryTitle: 'Resumen ejecutivo',
      executiveSummaryCopy: 'Vista compacta para reportes semanales y revisiones con stakeholders.',
      averageRating: 'Puntuacion media',
      feedbackCount: 'Cantidad de feedback',
      satisfactionRate: 'Tasa de satisfaccion',
      currentWindow: 'Ventana actual',
    },
    feedback: {
      title: 'Lista de feedback',
      copy: 'Busca comentarios, ordena por puntuacion o fecha y abre el detalle en un panel lateral.',
      tableDate: 'Fecha',
      tableScore: 'Puntuacion',
      tableWeakestArea: 'Area mas debil',
      tableComment: 'Comentario',
      tableStatus: 'Estado',
      emptyTitle: 'Ningun feedback coincide con estos filtros',
      emptyCopy:
        'Prueba un rango mas amplio o limpia la combinacion activa de busqueda, filtro y orden.',
    },
    operations: {
      currentLocationTitle: 'Resumen de la ubicacion actual',
      currentLocationCopy:
        'Hoy el espacio representa una sola entidad de negocio, por eso este panel funciona como vista en vivo.',
      location: 'Ubicacion',
      city: 'Ciudad',
      sector: 'Sector',
      latestFeedback: 'Ultimo feedback',
      noFeedbackYet: 'Todavia no hay feedback',
      branchesTitle: 'Sucursales y ubicaciones',
      branchesCopy:
        'Preparado para analitica multiubicacion sin ocultar los limites actuales del backend.',
      branchesEmptyTitle: 'La comparacion entre sucursales aun no esta disponible',
      branchesEmptyCopy:
        'El backend hoy almacena un solo espacio de negocio sin entidades de sucursal ni propiedad por ubicacion.',
      serviceInsightsTitle: 'Insights de servicio',
      serviceInsightsCopy:
        'Lectura operativa de las categorias mas debiles, incluso sin seguimiento por empleado.',
      serviceInsightsEmptyTitle: 'No hay suficiente senal operativa',
      serviceInsightsEmptyCopy:
        'A medida que lleguen mas respuestas, sera mas facil separar problemas reales del ruido.',
      checklistTitle: 'Checklist operativa',
      checklistCopy: 'Acciones sugeridas para managers segun el estado actual del producto y los datos.',
      checklistLowScoreTitle: 'Revisar a diario el feedback con baja puntuacion',
      checklistLowScoreNone:
        'No hay respuestas con baja puntuacion apareciendo en esta ventana de reporte.',
      checklistFormTitle: 'Mantener el formulario activo alineado con la operacion',
      checklistFormNone: 'Todavia no hay preguntas activas configuradas.',
      checklistCommentTitle: 'Mejorar el contexto escrito de los clientes',
      checklistCommentGoodTail: 'lo que aporta mejor detalle cualitativo.',
      checklistCommentLowTail:
        'asi que el diagnostico sigue dependiendo mucho de los patrones de puntuacion.',
      checklistDimensionsTitle: 'Preparar dimensiones de sucursal y personal',
      checklistDimensionsCopy:
        'Las vistas multiubicacion y de personal requieren tablas backend para ubicaciones, personal y relaciones de envio.',
    },
    collection: {
      overviewTitle: 'Resumen de captacion',
      overviewCopy:
        'Lectura en vivo de si el flujo publico, el desvio a reviews y los activos del formulario estan listos para clientes.',
      statusLiveForm: 'Formulario activo',
      statusPublicAccess: 'Acceso publico',
      statusQrAsset: 'Activo QR',
      statusChannels: 'Preparacion de canales',
      statusLiveFormReady: 'Configurado y listo para recopilar feedback.',
      statusLiveFormMissing: 'No hay un formulario de feedback asociado actualmente a este espacio.',
      statusPublicReady: 'Los clientes pueden abrir el formulario activo de inmediato desde la URL publica.',
      statusPublicMissing:
        'La ruta publica existe, pero el formulario aun necesita preguntas activas para sentirse completo.',
      statusQrReady: 'La generacion de QR esta disponible para el espacio actual.',
      statusQrMissing: 'El QR todavia no esta marcado como generado en el modelo de datos actual.',
      statusChannelsReady: 'Marca y enlaces de destino listos para distribucion.',
      statusChannelsMissing:
        'Completa la marca o agrega un destino externo de review antes de un lanzamiento amplio.',
      distributionTitle: 'Canales de distribucion',
      distributionCopy:
        'Comparte el formulario activo con confianza en materiales del local, flujos de review y puntos de contacto.',
      liveUrlTitle: 'URL publica del formulario',
      liveUrlCopy: 'Punto de entrada principal para que los clientes dejen feedback directo.',
      liveUrlHint: 'Usa este enlace en recibos, kioscos, mensajes o material impreso.',
      reviewLinkTitle: 'Ruta de Google reviews',
      reviewLinkCopy:
        'Destino secundario para captar opiniones publicas cuando un cliente quiere publicar externamente.',
      reviewLinkMissing: 'Agrega una URL de Google reviews para completar la ruta externa.',
      reviewLinkHint:
        'Mantener este destino actualizado hace mas confiable el traspaso desde QR y otros canales.',
      qrTitle: 'Activo QR para distribucion',
      qrCopy: 'Descarga o actualiza el QR imprimible que apunta directamente al formulario activo.',
      qrHint: 'Usa un QR limpio en mostradores, mesas, empaques y puntos de contacto post-servicio.',
      questionStudioTitle: 'Gestion de preguntas',
      questionStudioCopy:
        'Mantiene el set de preguntas activas con mejor estructura, control de borradores y publicacion clara.',
      questionStudioMetricLive: 'Preguntas activas',
      questionStudioMetricDraft: 'Estado del borrador',
      questionStudioMetricCoverage: 'Cobertura de idiomas',
      questionStudioMetricStatus: 'Estado de captacion',
      questionStudioDraftClean: 'El borrador coincide con el formulario activo',
      questionStudioDraftPending: 'Hay cambios listos para publicar',
      questionStudioCoverageReady: 'Todas las etiquetas publicas estan cubiertas',
      questionStudioCoveragePartial:
        'Algunas traducciones todavia dependen de otro idioma',
      questionStudioStatusReady: 'La publicacion esta disponible ahora',
      questionStudioStatusBlocked: 'Se requiere un formulario activo antes de publicar',
      questionStudioListTitle: 'Borrador actual',
      questionStudioListCopy:
        'Reordena, ajusta y revisa las preguntas que estructuran el feedback.',
      questionStudioComposerTitle: 'Agregar nueva pregunta al borrador',
      questionStudioComposerCopy:
        'Empieza por la etiqueta en frances y despues completa los otros idiomas para mantener coherencia.',
      questionEmptyTitle: 'No hay preguntas configuradas',
      questionEmptyCopy:
        'Crea la primera pregunta abajo para empezar a recopilar feedback estructurado.',
      brandingTitle: 'Marca y canales',
      brandingCopy:
        'Mantiene los activos de captacion profesionales alineando logo y destinos externos.',
      brandIdentityTitle: 'Identidad de marca',
      brandIdentityCopy:
        'El logo mostrado en los materiales de distribucion debe coincidir con lo que los clientes reconocen al instante.',
      channelConfigTitle: 'Configuracion de canales',
      channelConfigCopy:
        'Controla adonde llegan los clientes despues y asegura una captacion publica coherente en cada canal.',
      destinationLabel: 'Destino de Google reviews',
      destinationPlaceholder: 'https://...',
      destinationHint:
        'Este enlace se reutiliza en el espacio de distribucion y debe apuntar al destino activo.',
      logoHint:
        'Sube un logo cuadrado limpio para exportaciones QR, materiales impresos y puntos publicos de captacion.',
      openDestination: 'Abrir destino',
    },
    settings: {
      businessTitle: 'Configuracion del negocio',
      businessCopy: 'Datos principales del espacio usados en toda la experiencia de feedback.',
      businessName: 'Nombre del negocio',
      plan: 'Plan',
      googleReviewUrl: 'URL de Google reviews',
      planStatus: 'Estado del plan',
      brandingTitle: 'Marca y espacio',
      brandingCopy: 'Mantiene el espacio admin pulido y alineado con la marca.',
      workspaceOwner: 'Propietario del espacio',
      planGuidance: 'Guia del plan',
    },
  },
  ar: {
    ...EN_DASHBOARD_COPY,
    sections: {
      overview: {
        label: 'نظرة عامة',
        description: 'مؤشرات اساسية، تنبيهات الخدمة، وقراءة سريعة لرضا العملاء.',
      },
      analytics: {
        label: 'التحليلات',
        description: 'الاتجاهات، توزيع التقييمات، وتحليل الملاحظات حسب السؤال.',
      },
      feedback: {
        label: 'الملاحظات',
        description: 'ابحث وصف وراجع كل رد من العملاء بشكل مفصل.',
      },
      operations: {
        label: 'العمليات',
        description: 'جاهزية التشغيل، مشاكل الخدمة، والمتابعة اليومية.',
      },
      collection: {
        label: 'التحصيل',
        description: 'الوصول العام للنموذج، ملفات QR، وادارة الاسئلة.',
      },
      settings: {
        label: 'الاعدادات',
        description: 'ملف النشاط، الهوية، حالة الخطة، وعناصر التحكم في المساحة.',
      },
    },
    common: {
      ...EN_DASHBOARD_COPY.common,
      brandTagline: 'مساحة ملاحظات العملاء',
      dataLimitationsTitle: 'قيود البيانات',
      dataLimitationsCopy:
        'تحليلات الفروع والموظفين ستبقى في وضع placeholder حتى يدعمها الـ backend بشكل صريح.',
      open: 'فتح',
      save: 'حفظ',
      saveChanges: 'حفظ التغييرات',
      publishChanges: 'نشر التغييرات',
      addQuestion: 'اضافة سؤال',
      downloadPng: 'تنزيل PNG',
      refreshPreview: 'تحديث المعاينة',
      openForm: 'فتح النموذج',
      copyFormLink: 'نسخ رابط النموذج',
      copiedLink: 'تم نسخ الرابط',
      copyFailed: 'فشل النسخ',
      openNavigation: 'فتح التنقل',
      closeNavigation: 'اغلاق التنقل',
      collapseSidebar: 'تصغير الشريط الجانبي',
      expandSidebar: 'توسيع الشريط الجانبي',
      reportingRange: 'فترة التقرير',
      trendResolution: 'مستوى الاتجاه',
      analyticsTrendResolution: 'مستوى اتجاه التحليلات',
      searchFeedback: 'البحث في الملاحظات',
      filterFeedback: 'تصفية الملاحظات',
      sortFeedback: 'ترتيب الملاحظات',
      searchPlaceholder: 'ابحث في التعليقات او اسماء الاسئلة',
      noData: 'لا توجد بيانات',
      noCategory: 'بدون فئة',
      noWrittenComment: 'لا يوجد تعليق مكتوب',
      noWrittenCommentLong: 'لم يترك العميل تعليقا مكتوبا في هذا الرد.',
      noScore: 'بدون تقييم',
      positive: 'ايجابي',
      neutral: 'محايد',
      attention: 'يحتاج متابعة',
      status: 'الحالة',
      weakestQuestion: 'اضعف سؤال',
      questionScores: 'درجات الاسئلة',
      customerComment: 'تعليق العميل',
      feedbackDetails: 'تفاصيل الملاحظة',
      closeFeedbackDetails: 'اغلاق تفاصيل الملاحظة',
      submitted: 'تم الارسال',
      overallScoreSuffix: 'التقييم العام',
      questionWord: 'سؤال',
      newQuestion: 'سؤال جديد',
      draftQuestion: 'سؤال مسودة',
      frenchLabel: 'النص الفرنسي',
      arabicLabel: 'النص العربي',
      englishLabel: 'النص الانجليزي',
      spanishLabel: 'النص الاسباني',
      responseSingular: 'رد',
      responsePlural: 'ردود',
      resultSingular: 'نتيجة',
      resultPlural: 'نتائج',
      questionSingular: 'سؤال',
      questionPlural: 'اسئلة',
      itemSingular: 'عنصر',
      itemPlural: 'عناصر',
      ratedAreaSingular: 'عنصر مقيم',
      ratedAreaPlural: 'عناصر مقيمة',
      lastUpdated: 'اخر تحديث',
      publicAccess: 'الوصول العام',
      qrAvailability: 'توفر QR',
      liveStatus: 'الحالة المباشرة',
      ready: 'جاهز',
      needsAttention: 'يحتاج متابعة',
      inactive: 'غير نشط',
      notConfigured: 'غير مضبوط',
      lastDaysPrefix: 'اخر',
      lastDaysSuffix: 'يوما',
      previousPeriodFlat: 'ثابت مقارنة بالفترة السابقة',
      previousPeriodSuffix: 'مقارنة بالفترة السابقة',
      pointsSuffix: ' نقطة',
      lowScoreShare: 'نسبة التقييمات المنخفضة',
      questionLimit: 'حد 10 اسئلة',
      signedInUser: 'المستخدم الحالي',
      replaceLogo: 'استبدال الشعار',
      uploadLogo: 'رفع شعار',
      logoUploaded: 'تم رفع الشعار',
      noLogoYet: 'لا يوجد شعار بعد',
      signOut: 'تسجيل الخروج',
      tryAgain: 'المحاولة مرة اخرى',
      dashboardLoadError: 'تعذر تحميل لوحة التحكم',
      dashboardLoadErrorCopy:
        'حدث خطا اثناء تجهيز المساحة. حاول مرة اخرى لاعادة تحميل احدث البيانات.',
      noStructuredRatingsTitle: 'لا توجد تقييمات تفصيلية',
      noStructuredRatingsCopy:
        'هذا الرد يحتوي فقط على التقييم العام واي تعليق مكتوب.',
    },
    header: {
      eyebrow: 'لوحة مساحة العمل',
      updating: 'يتم تحديث عرض المساحة',
    },
    options: {
      resolutions: { day: 'يوم', week: 'اسبوع', month: 'شهر' },
      feedbackFilters: {
        all: 'الكل',
        attention: 'يحتاج متابعة',
        positive: 'ايجابي',
        commented: 'مع تعليق',
      },
      feedbackSorts: {
        newest: 'الترتيب: الاحدث',
        oldest: 'الترتيب: الاقدم',
        highest: 'الترتيب: الاعلى تقييما',
        lowest: 'الترتيب: الاقل تقييما',
      },
      planStatuses: {
        active: 'نشط',
        trial: 'تجريبي',
        past_due: 'متاخر السداد',
        suspended: 'موقوف',
      },
    },
    notices: {
      settingsSaved: 'تم تحديث اعدادات النشاط بنجاح.',
      settingsError: 'تعذر حفظ اعدادات النشاط.',
      logoSaved: 'تم تحديث شعار العلامة بنجاح.',
      logoError: 'تعذر رفع الشعار.',
      questionLimit: 'يمكن للنموذج ان يحتوي على 10 اسئلة كحد اقصى.',
      frenchRequired: 'يجب ادخال النص الفرنسي قبل اضافة سؤال جديد.',
      questionAdded: 'تمت اضافة السؤال الى مسودة النموذج.',
      keepOneQuestion: 'يجب ان يحتفظ النموذج بسؤال واحد على الاقل.',
      noForm: 'لا يوجد نموذج ملاحظات لهذا النشاط بعد.',
      publishNeedsQuestion: 'اضف سؤالا واحدا على الاقل قبل النشر.',
      publishError: 'تعذر نشر اسئلة النموذج.',
      publishSuccess: 'تم تحديث اسئلة النموذج المباشر بنجاح.',
    },
    overview: {
      ...EN_DASHBOARD_COPY.overview,
      metrics: {
        averageRating: 'متوسط التقييم',
        averageRatingNote: 'اتجاه الرضا العام خلال فترة التقرير المحددة.',
        totalFeedback: 'اجمالي الملاحظات',
        totalFeedbackNote: 'كل الردود المستلمة داخل نافذة التقرير الحالية.',
        satisfactionRate: 'نسبة الرضا',
        satisfactionRateNote: 'نسبة الردود التي حصلت على 4/5 او اكثر.',
        negativeAlerts: 'تنبيهات سلبية',
        negativeAlertsNote: 'ردود منخفضة التقييم تستحق مراجعة تشغيلية سريعة.',
      },
      responseTrendTitle: 'اتجاه الردود',
      responseTrendCopy: 'حجم الردود ومتوسط التقييم خلال فترة التقرير المحددة.',
      noFeedbackTitle: 'لا توجد ملاحظات في هذه الفترة',
      noFeedbackCopy: 'وسع الفترة الزمنية او انتظر ردودا جديدة لبدء ملء اللوحة.',
      watchlistTitle: 'قائمة المتابعة التشغيلية',
      watchlistCopy: 'اهم اشارات الخدمة والتجربة التي تستحق المراجعة الآن.',
      watchlistEmptyTitle: 'لا توجد مشاكل عاجلة',
      watchlistEmptyCopy:
        'نافذة البيانات الحالية تبدو مستقرة. ستظهر المخاطر الجديدة هنا عندما يتغير مستوى الملاحظات.',
      recentFeedbackTitle: 'احدث الملاحظات',
      recentFeedbackCopy: 'احدث ردود العملاء مع اسرع طريق للمراجعة التفصيلية.',
      recentFeedbackEmptyTitle: 'لا توجد ملاحظات حديثة بعد',
      recentFeedbackEmptyCopy:
        'بمجرد ان يرسل العملاء ملاحظاتهم ستظهر احدث الردود هنا.',
      performanceSnapshotTitle: 'ملخص الاداء',
      performanceSnapshotCopy:
        'قراءة مختصرة لصحة الخدمة وجودة الفئات ونسبة التعليقات المكتوبة.',
      strongestCategory: 'افضل فئة',
      weakestCategory: 'اضعف فئة',
      commentCoverage: 'تغطية التعليقات',
      feedbackMix: 'مزيج الملاحظات',
      noCategoryData: 'لا توجد بيانات فئات بعد',
      watchlistAttentionCopy:
        'الدرجات الاقل من 3/5 تشير الى فرص استرجاع خدمة يجب مراجعتها بسرعة.',
      watchlistWeakestTitleSuffix: 'هي اضعف منطقة خدمة حاليا',
      watchlistWeakestCopySuffix: 'كمتوسط مع',
      watchlistWeakestCopyTail: 'داخل الفترة المحددة.',
      watchlistDriftTitle: 'متوسط التقييم يتراجع مقارنة بالفترة السابقة',
      watchlistDriftCopyTail: 'راجع اخر التعليقات السلبية للحصول على السياق.',
      watchlistCommentTitle: 'التعليقات المكتوبة ما تزال قليلة',
      watchlistCommentCopyPrefix: 'فقط',
      watchlistCommentCopySuffix:
        'من العملاء تركوا تعليقا مكتوبا، وهذا يحد من تشخيص المشاكل.',
    },
    analytics: {
      ...EN_DASHBOARD_COPY.analytics,
      ratingsTrendTitle: 'اتجاه التقييمات',
      ratingsTrendCopy:
        'تابع حجم الردود ومتوسط التقييم عبر اليوم او الاسبوع او الشهر.',
      trendEmptyTitle: 'التحليلات تحتاج بيانات احدث',
      trendEmptyCopy: 'لا توجد ملاحظات كافية في هذه الفترة لبناء اتجاه موثوق.',
      ratingsDistributionTitle: 'توزيع التقييمات',
      ratingsDistributionCopy: 'تفصيل درجة بدرجة للتجربة العامة.',
      distributionEmptyTitle: 'التوزيع غير متاح',
      distributionEmptyCopy:
        'يصبح توزيع الدرجات مفيدا عندما تحتوي الفترة المحددة على ملاحظات حقيقية.',
      sentimentMixAria: 'مزيج شعور الملاحظات',
      questionPerformanceTitle: 'اداء الاسئلة',
      questionPerformanceCopy:
        'قراءة سؤال بسؤال لفهم ما يقدره العملاء واين تتراجع الخدمة.',
      questionEmptyTitle: 'تحليلات الاسئلة تحتاج بيانات اكثر',
      questionEmptyCopy:
        'ستظهر الرؤى الخاصة بكل سؤال بمجرد ان يبدأ العملاء بتقييم اسئلة النموذج المباشر.',
      recurringIssuesTitle: 'المشاكل المتكررة',
      recurringIssuesCopy:
        'الفئات الضعيفة التي تتكرر بما يكفي لتستحق اجراء تشغيليا.',
      recurringIssuesEmptyTitle: 'لا يوجد نمط متكرر حاليا',
      recurringIssuesEmptyCopy:
        'عندما يصبح سؤال ما مشكلة مستمرة سيتم ابرازه هنا.',
      executiveSummaryTitle: 'ملخص تنفيذي',
      executiveSummaryCopy: 'عرض مختصر للتقارير الاسبوعية ومراجعات الادارة.',
      averageRating: 'متوسط التقييم',
      feedbackCount: 'عدد الملاحظات',
      satisfactionRate: 'نسبة الرضا',
      currentWindow: 'الفترة الحالية',
    },
    feedback: {
      title: 'قائمة الملاحظات',
      copy: 'ابحث في التعليقات، رتب حسب الدرجة او التاريخ، وافتح كل رد داخل لوحة جانبية.',
      tableDate: 'التاريخ',
      tableScore: 'الدرجة',
      tableWeakestArea: 'اضعف نقطة',
      tableComment: 'التعليق',
      tableStatus: 'الحالة',
      emptyTitle: 'لا توجد نتائج لهذه التصفية',
      emptyCopy:
        'جرب فترة اوسع او امسح البحث والتصفية والترتيب الحالي.',
    },
    operations: {
      currentLocationTitle: 'ملخص الموقع الحالي',
      currentLocationCopy:
        'في الوقت الحالي تمثل المساحة نشاطا واحدا فقط، لذلك يعمل هذا القسم كعرض مباشر للموقع.',
      location: 'الموقع',
      city: 'المدينة',
      sector: 'القطاع',
      latestFeedback: 'اخر ملاحظة',
      noFeedbackYet: 'لا توجد ملاحظات بعد',
      branchesTitle: 'الفروع والمواقع',
      branchesCopy:
        'جاهز لتحليلات متعددة المواقع مع الالتزام بوضوح حدود الـ backend الحالية.',
      branchesEmptyTitle: 'مقارنة الفروع غير متاحة بعد',
      branchesEmptyCopy:
        'الـ backend الحالي يخزن مساحة نشاط واحدة فقط دون كيانات للفروع او ملكية للردود حسب الموقع.',
      serviceInsightsTitle: 'رؤى الخدمة',
      serviceInsightsCopy:
        'قراءة تشغيلية للفئات الاضعف حتى قبل وجود تتبع على مستوى الموظفين.',
      serviceInsightsEmptyTitle: 'لا توجد اشارة تشغيلية كافية',
      serviceInsightsEmptyCopy:
        'كلما وصلت ردود اكثر يصبح من الاسهل فصل المشاكل الحقيقية عن الضوضاء.',
      checklistTitle: 'قائمة تشغيلية',
      checklistCopy: 'مهام مقترحة للمديرين بناء على جاهزية المنتج والبيانات الحالية.',
      checklistLowScoreTitle: 'راجع الردود منخفضة التقييم يوميا',
      checklistLowScoreNone:
        'لا توجد حاليا ردود منخفضة التقييم داخل نافذة التقرير هذه.',
      checklistFormTitle: 'حافظ على توافق النموذج المباشر مع التشغيل',
      checklistFormNone: 'لا توجد اسئلة مباشرة مضبوطة حتى الآن.',
      checklistCommentTitle: 'حسن السياق المكتوب من الضيوف',
      checklistCommentGoodTail: 'وهذا يعطي تفاصيل نوعية افضل.',
      checklistCommentLowTail:
        'لذلك ما زال التشخيص يعتمد بشكل كبير على نمط الدرجات.',
      checklistDimensionsTitle: 'جهز بعدي الفروع والموظفين',
      checklistDimensionsCopy:
        'رؤية الفروع والموظفين تحتاج جداول backend للمواقع والموظفين وربطها بالردود.',
    },
    collection: {
      overviewTitle: 'نظرة عامة على التحصيل',
      overviewCopy:
        'قراءة مباشرة لحالة النموذج العام، تحويلات المراجعات، وملفات جمع الملاحظات.',
      statusLiveForm: 'النموذج المباشر',
      statusPublicAccess: 'الوصول العام',
      statusQrAsset: 'ملف QR',
      statusChannels: 'جاهزية القنوات',
      statusLiveFormReady: 'تم ضبطه وجاهز لاستقبال الملاحظات.',
      statusLiveFormMissing: 'لا يوجد نموذج ملاحظات مرتبط بهذه المساحة حاليا.',
      statusPublicReady: 'يمكن للضيوف فتح النموذج المباشر مباشرة من الرابط العام.',
      statusPublicMissing:
        'المسار العام موجود لكن النموذج ما زال يحتاج اسئلة مباشرة ليصبح جاهزا بالكامل.',
      statusQrReady: 'توليد QR متاح لهذه المساحة.',
      statusQrMissing: 'لم يتم تعليم QR كمولد بعد داخل نموذج البيانات الحالي.',
      statusChannelsReady: 'الشعار وروابط الوجهة جاهزة للتوزيع.',
      statusChannelsMissing:
        'اكمل الهوية او اضف رابط مراجعات خارجي قبل التوزيع الواسع.',
      distributionTitle: 'قنوات التوزيع',
      distributionCopy:
        'شارك النموذج المباشر بثقة عبر المواد داخل الموقع، تدفقات المراجعات، ونقاط التواصل مع العميل.',
      liveUrlTitle: 'رابط النموذج العام',
      liveUrlCopy: 'بوابة العميل الرئيسية لجمع الملاحظات المباشرة.',
      liveUrlHint: 'استخدم هذا الرابط على الفواتير، الاكشاك، الرسائل، او المواد المطبوعة.',
      reviewLinkTitle: 'تحويل Google reviews',
      reviewLinkCopy:
        'وجهة ثانوية لجمع المراجعات العامة عندما يريد العميل النشر خارجيا.',
      reviewLinkMissing: 'اضف رابط Google reviews لاكمال مسار المراجعات الخارجية.',
      reviewLinkHint:
        'ابق هذه الوجهة محدثة حتى يبقى الانتقال من QR والقنوات واضحا وموثوقا.',
      qrTitle: 'ملف QR للتوزيع',
      qrCopy: 'قم بتنزيل او تحديث QR القابل للطباعة الذي يفتح النموذج المباشر مباشرة.',
      qrHint: 'استخدم QR واضحا على الطاولات والكاونترات والتغليف ونقاط ما بعد الخدمة.',
      questionStudioTitle: 'ادارة الاسئلة',
      questionStudioCopy:
        'ادارة مجموعة الاسئلة المباشرة بهيكل اوضح وتحكم افضل في المسودة والنشر.',
      questionStudioMetricLive: 'الاسئلة المباشرة',
      questionStudioMetricDraft: 'حالة المسودة',
      questionStudioMetricCoverage: 'تغطية اللغات',
      questionStudioMetricStatus: 'حالة التحصيل',
      questionStudioDraftClean: 'المسودة مطابقة للنموذج المباشر',
      questionStudioDraftPending: 'هناك تغييرات جاهزة للنشر',
      questionStudioCoverageReady: 'كل النصوص العامة مغطاة',
      questionStudioCoveragePartial:
        'بعض الترجمات ما تزال تعتمد على لغة بديلة',
      questionStudioStatusReady: 'يمكن النشر الآن',
      questionStudioStatusBlocked: 'يلزم وجود نموذج مباشر قبل النشر',
      questionStudioListTitle: 'المسودة الحالية',
      questionStudioListCopy:
        'اعد ترتيب الاسئلة وحررها وراجعها قبل نشرها على النموذج المباشر.',
      questionStudioComposerTitle: 'اضافة سؤال جديد للمسودة',
      questionStudioComposerCopy:
        'ابدأ بالنص الفرنسي ثم اكمل باقي اللغات حتى يبقى النموذج متسقا.',
      questionEmptyTitle: 'لا توجد اسئلة مضبوطة',
      questionEmptyCopy:
        'انشئ اول سؤال بالاسفل لبدء جمع ملاحظات العملاء بشكل منظم.',
      brandingTitle: 'الهوية والقنوات',
      brandingCopy:
        'اجعل مواد التحصيل اكثر احترافية من خلال توحيد الشعار وروابط الوجهات.',
      brandIdentityTitle: 'هوية العلامة',
      brandIdentityCopy:
        'يجب ان يطابق الشعار الظاهر على مواد التوزيع ما يتعرف عليه الضيف مباشرة.',
      channelConfigTitle: 'اعدادات القنوات',
      channelConfigCopy:
        'تحكم في الوجهة التالية للعميل وحافظ على تجربة تحصيل عامة واضحة عبر كل القنوات.',
      destinationLabel: 'وجهة Google reviews',
      destinationPlaceholder: 'https://...',
      destinationHint:
        'يتم اعادة استخدام هذا الرابط في مساحة التوزيع ويجب ان يشير الى الوجهة الفعلية.',
      logoHint:
        'ارفع شعارا مربعا وواضحا لاستخدامه في ملفات QR والمواد المطبوعة ونقاط التحصيل العامة.',
      openDestination: 'فتح الوجهة',
    },
    settings: {
      businessTitle: 'اعدادات النشاط',
      businessCopy: 'بيانات المساحة الاساسية المستخدمة في كل تجربة الملاحظات.',
      businessName: 'اسم النشاط',
      plan: 'الخطة',
      googleReviewUrl: 'رابط Google reviews',
      planStatus: 'حالة الخطة',
      brandingTitle: 'الهوية ومساحة العمل',
      brandingCopy: 'حافظ على مساحة الادارة بشكل احترافي ومتسق مع العلامة.',
      workspaceOwner: 'مالك المساحة',
      planGuidance: 'توجيه الخطة',
    },
  },
} as const

type WidenLiterals<T> = T extends string
  ? string
  : T extends number
    ? number
    : T extends boolean
      ? boolean
      : { [K in keyof T]: WidenLiterals<T[K]> }

export type DashboardCopy = WidenLiterals<typeof EN_DASHBOARD_COPY>
